/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.opencps.processmgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ActionHistory service. Represents a row in the &quot;opencps_actionhistory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.opencps.processmgt.model.impl.ActionHistoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.opencps.processmgt.model.impl.ActionHistoryImpl}.
 * </p>
 *
 * @author khoavd
 * @see ActionHistory
 * @see org.opencps.processmgt.model.impl.ActionHistoryImpl
 * @see org.opencps.processmgt.model.impl.ActionHistoryModelImpl
 * @generated
 */
public interface ActionHistoryModel extends BaseModel<ActionHistory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a action history model instance should use the {@link ActionHistory} interface instead.
	 */

	/**
	 * Returns the primary key of this action history.
	 *
	 * @return the primary key of this action history
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this action history.
	 *
	 * @param primaryKey the primary key of this action history
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the action history ID of this action history.
	 *
	 * @return the action history ID of this action history
	 */
	public long getActionHistoryId();

	/**
	 * Sets the action history ID of this action history.
	 *
	 * @param actionHistoryId the action history ID of this action history
	 */
	public void setActionHistoryId(long actionHistoryId);

	/**
	 * Returns the company ID of this action history.
	 *
	 * @return the company ID of this action history
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this action history.
	 *
	 * @param companyId the company ID of this action history
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this action history.
	 *
	 * @return the group ID of this action history
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this action history.
	 *
	 * @param groupId the group ID of this action history
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this action history.
	 *
	 * @return the user ID of this action history
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this action history.
	 *
	 * @param userId the user ID of this action history
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this action history.
	 *
	 * @return the user uuid of this action history
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this action history.
	 *
	 * @param userUuid the user uuid of this action history
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this action history.
	 *
	 * @return the create date of this action history
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this action history.
	 *
	 * @param createDate the create date of this action history
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this action history.
	 *
	 * @return the modified date of this action history
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this action history.
	 *
	 * @param modifiedDate the modified date of this action history
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the process order ID of this action history.
	 *
	 * @return the process order ID of this action history
	 */
	public long getProcessOrderId();

	/**
	 * Sets the process order ID of this action history.
	 *
	 * @param processOrderId the process order ID of this action history
	 */
	public void setProcessOrderId(long processOrderId);

	/**
	 * Returns the process workflow ID of this action history.
	 *
	 * @return the process workflow ID of this action history
	 */
	public long getProcessWorkflowId();

	/**
	 * Sets the process workflow ID of this action history.
	 *
	 * @param processWorkflowId the process workflow ID of this action history
	 */
	public void setProcessWorkflowId(long processWorkflowId);

	/**
	 * Returns the action datetime of this action history.
	 *
	 * @return the action datetime of this action history
	 */
	public Date getActionDatetime();

	/**
	 * Sets the action datetime of this action history.
	 *
	 * @param actionDatetime the action datetime of this action history
	 */
	public void setActionDatetime(Date actionDatetime);

	/**
	 * Returns the step name of this action history.
	 *
	 * @return the step name of this action history
	 */
	@AutoEscape
	public String getStepName();

	/**
	 * Sets the step name of this action history.
	 *
	 * @param stepName the step name of this action history
	 */
	public void setStepName(String stepName);

	/**
	 * Returns the action name of this action history.
	 *
	 * @return the action name of this action history
	 */
	@AutoEscape
	public String getActionName();

	/**
	 * Sets the action name of this action history.
	 *
	 * @param actionName the action name of this action history
	 */
	public void setActionName(String actionName);

	/**
	 * Returns the action note of this action history.
	 *
	 * @return the action note of this action history
	 */
	@AutoEscape
	public String getActionNote();

	/**
	 * Sets the action note of this action history.
	 *
	 * @param actionNote the action note of this action history
	 */
	public void setActionNote(String actionNote);

	/**
	 * Returns the action user ID of this action history.
	 *
	 * @return the action user ID of this action history
	 */
	public long getActionUserId();

	/**
	 * Sets the action user ID of this action history.
	 *
	 * @param actionUserId the action user ID of this action history
	 */
	public void setActionUserId(long actionUserId);

	/**
	 * Returns the action user uuid of this action history.
	 *
	 * @return the action user uuid of this action history
	 * @throws SystemException if a system exception occurred
	 */
	public String getActionUserUuid() throws SystemException;

	/**
	 * Sets the action user uuid of this action history.
	 *
	 * @param actionUserUuid the action user uuid of this action history
	 */
	public void setActionUserUuid(String actionUserUuid);

	/**
	 * Returns the days doing of this action history.
	 *
	 * @return the days doing of this action history
	 */
	public int getDaysDoing();

	/**
	 * Sets the days doing of this action history.
	 *
	 * @param daysDoing the days doing of this action history
	 */
	public void setDaysDoing(int daysDoing);

	/**
	 * Returns the days delay of this action history.
	 *
	 * @return the days delay of this action history
	 */
	public int getDaysDelay();

	/**
	 * Sets the days delay of this action history.
	 *
	 * @param daysDelay the days delay of this action history
	 */
	public void setDaysDelay(int daysDelay);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.opencps.processmgt.model.ActionHistory actionHistory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.opencps.processmgt.model.ActionHistory> toCacheModel();

	@Override
	public org.opencps.processmgt.model.ActionHistory toEscapedModel();

	@Override
	public org.opencps.processmgt.model.ActionHistory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}