/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.opencps.processmgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ProcessWorkflow service. Represents a row in the &quot;opencps_processworkflow&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.opencps.processmgt.model.impl.ProcessWorkflowModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.opencps.processmgt.model.impl.ProcessWorkflowImpl}.
 * </p>
 *
 * @author khoavd
 * @see ProcessWorkflow
 * @see org.opencps.processmgt.model.impl.ProcessWorkflowImpl
 * @see org.opencps.processmgt.model.impl.ProcessWorkflowModelImpl
 * @generated
 */
public interface ProcessWorkflowModel extends BaseModel<ProcessWorkflow> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a process workflow model instance should use the {@link ProcessWorkflow} interface instead.
	 */

	/**
	 * Returns the primary key of this process workflow.
	 *
	 * @return the primary key of this process workflow
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this process workflow.
	 *
	 * @param primaryKey the primary key of this process workflow
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the process workflow ID of this process workflow.
	 *
	 * @return the process workflow ID of this process workflow
	 */
	public long getProcessWorkflowId();

	/**
	 * Sets the process workflow ID of this process workflow.
	 *
	 * @param processWorkflowId the process workflow ID of this process workflow
	 */
	public void setProcessWorkflowId(long processWorkflowId);

	/**
	 * Returns the company ID of this process workflow.
	 *
	 * @return the company ID of this process workflow
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this process workflow.
	 *
	 * @param companyId the company ID of this process workflow
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this process workflow.
	 *
	 * @return the group ID of this process workflow
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this process workflow.
	 *
	 * @param groupId the group ID of this process workflow
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this process workflow.
	 *
	 * @return the user ID of this process workflow
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this process workflow.
	 *
	 * @param userId the user ID of this process workflow
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this process workflow.
	 *
	 * @return the user uuid of this process workflow
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this process workflow.
	 *
	 * @param userUuid the user uuid of this process workflow
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this process workflow.
	 *
	 * @return the create date of this process workflow
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this process workflow.
	 *
	 * @param createDate the create date of this process workflow
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this process workflow.
	 *
	 * @return the modified date of this process workflow
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this process workflow.
	 *
	 * @param modifiedDate the modified date of this process workflow
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the service process ID of this process workflow.
	 *
	 * @return the service process ID of this process workflow
	 */
	public long getServiceProcessId();

	/**
	 * Sets the service process ID of this process workflow.
	 *
	 * @param serviceProcessId the service process ID of this process workflow
	 */
	public void setServiceProcessId(long serviceProcessId);

	/**
	 * Returns the pre process step ID of this process workflow.
	 *
	 * @return the pre process step ID of this process workflow
	 */
	public long getPreProcessStepId();

	/**
	 * Sets the pre process step ID of this process workflow.
	 *
	 * @param preProcessStepId the pre process step ID of this process workflow
	 */
	public void setPreProcessStepId(long preProcessStepId);

	/**
	 * Returns the post process step ID of this process workflow.
	 *
	 * @return the post process step ID of this process workflow
	 */
	public long getPostProcessStepId();

	/**
	 * Sets the post process step ID of this process workflow.
	 *
	 * @param postProcessStepId the post process step ID of this process workflow
	 */
	public void setPostProcessStepId(long postProcessStepId);

	/**
	 * Returns the auto event of this process workflow.
	 *
	 * @return the auto event of this process workflow
	 */
	@AutoEscape
	public String getAutoEvent();

	/**
	 * Sets the auto event of this process workflow.
	 *
	 * @param autoEvent the auto event of this process workflow
	 */
	public void setAutoEvent(String autoEvent);

	/**
	 * Returns the action name of this process workflow.
	 *
	 * @return the action name of this process workflow
	 */
	@AutoEscape
	public String getActionName();

	/**
	 * Sets the action name of this process workflow.
	 *
	 * @param actionName the action name of this process workflow
	 */
	public void setActionName(String actionName);

	/**
	 * Returns the assign user of this process workflow.
	 *
	 * @return the assign user of this process workflow
	 */
	public boolean getAssignUser();

	/**
	 * Returns <code>true</code> if this process workflow is assign user.
	 *
	 * @return <code>true</code> if this process workflow is assign user; <code>false</code> otherwise
	 */
	public boolean isAssignUser();

	/**
	 * Sets whether this process workflow is assign user.
	 *
	 * @param assignUser the assign user of this process workflow
	 */
	public void setAssignUser(boolean assignUser);

	/**
	 * Returns the action user ID of this process workflow.
	 *
	 * @return the action user ID of this process workflow
	 */
	public long getActionUserId();

	/**
	 * Sets the action user ID of this process workflow.
	 *
	 * @param actionUserId the action user ID of this process workflow
	 */
	public void setActionUserId(long actionUserId);

	/**
	 * Returns the action user uuid of this process workflow.
	 *
	 * @return the action user uuid of this process workflow
	 * @throws SystemException if a system exception occurred
	 */
	public String getActionUserUuid() throws SystemException;

	/**
	 * Sets the action user uuid of this process workflow.
	 *
	 * @param actionUserUuid the action user uuid of this process workflow
	 */
	public void setActionUserUuid(String actionUserUuid);

	/**
	 * Returns the request payment of this process workflow.
	 *
	 * @return the request payment of this process workflow
	 */
	public boolean getRequestPayment();

	/**
	 * Returns <code>true</code> if this process workflow is request payment.
	 *
	 * @return <code>true</code> if this process workflow is request payment; <code>false</code> otherwise
	 */
	public boolean isRequestPayment();

	/**
	 * Sets whether this process workflow is request payment.
	 *
	 * @param requestPayment the request payment of this process workflow
	 */
	public void setRequestPayment(boolean requestPayment);

	/**
	 * Returns the payment fee of this process workflow.
	 *
	 * @return the payment fee of this process workflow
	 */
	@AutoEscape
	public String getPaymentFee();

	/**
	 * Sets the payment fee of this process workflow.
	 *
	 * @param paymentFee the payment fee of this process workflow
	 */
	public void setPaymentFee(String paymentFee);

	/**
	 * Returns the generate reception no of this process workflow.
	 *
	 * @return the generate reception no of this process workflow
	 */
	public boolean getGenerateReceptionNo();

	/**
	 * Returns <code>true</code> if this process workflow is generate reception no.
	 *
	 * @return <code>true</code> if this process workflow is generate reception no; <code>false</code> otherwise
	 */
	public boolean isGenerateReceptionNo();

	/**
	 * Sets whether this process workflow is generate reception no.
	 *
	 * @param generateReceptionNo the generate reception no of this process workflow
	 */
	public void setGenerateReceptionNo(boolean generateReceptionNo);

	/**
	 * Returns the reception no pattern of this process workflow.
	 *
	 * @return the reception no pattern of this process workflow
	 */
	@AutoEscape
	public String getReceptionNoPattern();

	/**
	 * Sets the reception no pattern of this process workflow.
	 *
	 * @param receptionNoPattern the reception no pattern of this process workflow
	 */
	public void setReceptionNoPattern(String receptionNoPattern);

	/**
	 * Returns the generate deadline of this process workflow.
	 *
	 * @return the generate deadline of this process workflow
	 */
	public boolean getGenerateDeadline();

	/**
	 * Returns <code>true</code> if this process workflow is generate deadline.
	 *
	 * @return <code>true</code> if this process workflow is generate deadline; <code>false</code> otherwise
	 */
	public boolean isGenerateDeadline();

	/**
	 * Sets whether this process workflow is generate deadline.
	 *
	 * @param generateDeadline the generate deadline of this process workflow
	 */
	public void setGenerateDeadline(boolean generateDeadline);

	/**
	 * Returns the deadline pattern of this process workflow.
	 *
	 * @return the deadline pattern of this process workflow
	 */
	@AutoEscape
	public String getDeadlinePattern();

	/**
	 * Sets the deadline pattern of this process workflow.
	 *
	 * @param deadlinePattern the deadline pattern of this process workflow
	 */
	public void setDeadlinePattern(String deadlinePattern);

	/**
	 * Returns the is finish step of this process workflow.
	 *
	 * @return the is finish step of this process workflow
	 */
	public boolean getIsFinishStep();

	/**
	 * Returns <code>true</code> if this process workflow is is finish step.
	 *
	 * @return <code>true</code> if this process workflow is is finish step; <code>false</code> otherwise
	 */
	public boolean isIsFinishStep();

	/**
	 * Sets whether this process workflow is is finish step.
	 *
	 * @param isFinishStep the is finish step of this process workflow
	 */
	public void setIsFinishStep(boolean isFinishStep);

	/**
	 * Returns the pre condition of this process workflow.
	 *
	 * @return the pre condition of this process workflow
	 */
	@AutoEscape
	public String getPreCondition();

	/**
	 * Sets the pre condition of this process workflow.
	 *
	 * @param preCondition the pre condition of this process workflow
	 */
	public void setPreCondition(String preCondition);

	/**
	 * Returns the is multipled of this process workflow.
	 *
	 * @return the is multipled of this process workflow
	 */
	public boolean getIsMultipled();

	/**
	 * Returns <code>true</code> if this process workflow is is multipled.
	 *
	 * @return <code>true</code> if this process workflow is is multipled; <code>false</code> otherwise
	 */
	public boolean isIsMultipled();

	/**
	 * Sets whether this process workflow is is multipled.
	 *
	 * @param isMultipled the is multipled of this process workflow
	 */
	public void setIsMultipled(boolean isMultipled);

	/**
	 * Returns the action code of this process workflow.
	 *
	 * @return the action code of this process workflow
	 */
	@AutoEscape
	public String getActionCode();

	/**
	 * Sets the action code of this process workflow.
	 *
	 * @param actionCode the action code of this process workflow
	 */
	public void setActionCode(String actionCode);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.opencps.processmgt.model.ProcessWorkflow processWorkflow);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.opencps.processmgt.model.ProcessWorkflow> toCacheModel();

	@Override
	public org.opencps.processmgt.model.ProcessWorkflow toEscapedModel();

	@Override
	public org.opencps.processmgt.model.ProcessWorkflow toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}