/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.opencps.processmgt.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import org.opencps.processmgt.service.persistence.ProcessStepDossierPartPK;

import java.io.Serializable;

/**
 * The base model interface for the ProcessStepDossierPart service. Represents a row in the &quot;opencps_processstep_dossierpart&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.opencps.processmgt.model.impl.ProcessStepDossierPartModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.opencps.processmgt.model.impl.ProcessStepDossierPartImpl}.
 * </p>
 *
 * @author khoavd
 * @see ProcessStepDossierPart
 * @see org.opencps.processmgt.model.impl.ProcessStepDossierPartImpl
 * @see org.opencps.processmgt.model.impl.ProcessStepDossierPartModelImpl
 * @generated
 */
public interface ProcessStepDossierPartModel extends BaseModel<ProcessStepDossierPart> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a process step dossier part model instance should use the {@link ProcessStepDossierPart} interface instead.
	 */

	/**
	 * Returns the primary key of this process step dossier part.
	 *
	 * @return the primary key of this process step dossier part
	 */
	public ProcessStepDossierPartPK getPrimaryKey();

	/**
	 * Sets the primary key of this process step dossier part.
	 *
	 * @param primaryKey the primary key of this process step dossier part
	 */
	public void setPrimaryKey(ProcessStepDossierPartPK primaryKey);

	/**
	 * Returns the process step ID of this process step dossier part.
	 *
	 * @return the process step ID of this process step dossier part
	 */
	public long getProcessStepId();

	/**
	 * Sets the process step ID of this process step dossier part.
	 *
	 * @param processStepId the process step ID of this process step dossier part
	 */
	public void setProcessStepId(long processStepId);

	/**
	 * Returns the dossier part ID of this process step dossier part.
	 *
	 * @return the dossier part ID of this process step dossier part
	 */
	public long getDossierPartId();

	/**
	 * Sets the dossier part ID of this process step dossier part.
	 *
	 * @param dossierPartId the dossier part ID of this process step dossier part
	 */
	public void setDossierPartId(long dossierPartId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.opencps.processmgt.model.ProcessStepDossierPart processStepDossierPart);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.opencps.processmgt.model.ProcessStepDossierPart> toCacheModel();

	@Override
	public org.opencps.processmgt.model.ProcessStepDossierPart toEscapedModel();

	@Override
	public org.opencps.processmgt.model.ProcessStepDossierPart toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}