/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.opencps.processmgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ProcessOrder service. Represents a row in the &quot;opencps_processorder&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.opencps.processmgt.model.impl.ProcessOrderModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.opencps.processmgt.model.impl.ProcessOrderImpl}.
 * </p>
 *
 * @author khoavd
 * @see ProcessOrder
 * @see org.opencps.processmgt.model.impl.ProcessOrderImpl
 * @see org.opencps.processmgt.model.impl.ProcessOrderModelImpl
 * @generated
 */
public interface ProcessOrderModel extends BaseModel<ProcessOrder> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a process order model instance should use the {@link ProcessOrder} interface instead.
	 */

	/**
	 * Returns the primary key of this process order.
	 *
	 * @return the primary key of this process order
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this process order.
	 *
	 * @param primaryKey the primary key of this process order
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the process order ID of this process order.
	 *
	 * @return the process order ID of this process order
	 */
	public long getProcessOrderId();

	/**
	 * Sets the process order ID of this process order.
	 *
	 * @param processOrderId the process order ID of this process order
	 */
	public void setProcessOrderId(long processOrderId);

	/**
	 * Returns the company ID of this process order.
	 *
	 * @return the company ID of this process order
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this process order.
	 *
	 * @param companyId the company ID of this process order
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this process order.
	 *
	 * @return the group ID of this process order
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this process order.
	 *
	 * @param groupId the group ID of this process order
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this process order.
	 *
	 * @return the user ID of this process order
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this process order.
	 *
	 * @param userId the user ID of this process order
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this process order.
	 *
	 * @return the user uuid of this process order
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this process order.
	 *
	 * @param userUuid the user uuid of this process order
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this process order.
	 *
	 * @return the create date of this process order
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this process order.
	 *
	 * @param createDate the create date of this process order
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this process order.
	 *
	 * @return the modified date of this process order
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this process order.
	 *
	 * @param modifiedDate the modified date of this process order
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the service info ID of this process order.
	 *
	 * @return the service info ID of this process order
	 */
	public long getServiceInfoId();

	/**
	 * Sets the service info ID of this process order.
	 *
	 * @param serviceInfoId the service info ID of this process order
	 */
	public void setServiceInfoId(long serviceInfoId);

	/**
	 * Returns the dossier template ID of this process order.
	 *
	 * @return the dossier template ID of this process order
	 */
	public long getDossierTemplateId();

	/**
	 * Sets the dossier template ID of this process order.
	 *
	 * @param dossierTemplateId the dossier template ID of this process order
	 */
	public void setDossierTemplateId(long dossierTemplateId);

	/**
	 * Returns the gov agency code of this process order.
	 *
	 * @return the gov agency code of this process order
	 */
	@AutoEscape
	public String getGovAgencyCode();

	/**
	 * Sets the gov agency code of this process order.
	 *
	 * @param govAgencyCode the gov agency code of this process order
	 */
	public void setGovAgencyCode(String govAgencyCode);

	/**
	 * Returns the gov agency name of this process order.
	 *
	 * @return the gov agency name of this process order
	 */
	@AutoEscape
	public String getGovAgencyName();

	/**
	 * Sets the gov agency name of this process order.
	 *
	 * @param govAgencyName the gov agency name of this process order
	 */
	public void setGovAgencyName(String govAgencyName);

	/**
	 * Returns the gov agency organization ID of this process order.
	 *
	 * @return the gov agency organization ID of this process order
	 */
	public long getGovAgencyOrganizationId();

	/**
	 * Sets the gov agency organization ID of this process order.
	 *
	 * @param govAgencyOrganizationId the gov agency organization ID of this process order
	 */
	public void setGovAgencyOrganizationId(long govAgencyOrganizationId);

	/**
	 * Returns the service process ID of this process order.
	 *
	 * @return the service process ID of this process order
	 */
	public long getServiceProcessId();

	/**
	 * Sets the service process ID of this process order.
	 *
	 * @param serviceProcessId the service process ID of this process order
	 */
	public void setServiceProcessId(long serviceProcessId);

	/**
	 * Returns the dossier ID of this process order.
	 *
	 * @return the dossier ID of this process order
	 */
	public long getDossierId();

	/**
	 * Sets the dossier ID of this process order.
	 *
	 * @param dossierId the dossier ID of this process order
	 */
	public void setDossierId(long dossierId);

	/**
	 * Returns the file group ID of this process order.
	 *
	 * @return the file group ID of this process order
	 */
	public long getFileGroupId();

	/**
	 * Sets the file group ID of this process order.
	 *
	 * @param fileGroupId the file group ID of this process order
	 */
	public void setFileGroupId(long fileGroupId);

	/**
	 * Returns the process step ID of this process order.
	 *
	 * @return the process step ID of this process order
	 */
	public long getProcessStepId();

	/**
	 * Sets the process step ID of this process order.
	 *
	 * @param processStepId the process step ID of this process order
	 */
	public void setProcessStepId(long processStepId);

	/**
	 * Returns the action user ID of this process order.
	 *
	 * @return the action user ID of this process order
	 */
	public long getActionUserId();

	/**
	 * Sets the action user ID of this process order.
	 *
	 * @param actionUserId the action user ID of this process order
	 */
	public void setActionUserId(long actionUserId);

	/**
	 * Returns the action user uuid of this process order.
	 *
	 * @return the action user uuid of this process order
	 * @throws SystemException if a system exception occurred
	 */
	public String getActionUserUuid() throws SystemException;

	/**
	 * Sets the action user uuid of this process order.
	 *
	 * @param actionUserUuid the action user uuid of this process order
	 */
	public void setActionUserUuid(String actionUserUuid);

	/**
	 * Returns the action datetime of this process order.
	 *
	 * @return the action datetime of this process order
	 */
	public Date getActionDatetime();

	/**
	 * Sets the action datetime of this process order.
	 *
	 * @param actionDatetime the action datetime of this process order
	 */
	public void setActionDatetime(Date actionDatetime);

	/**
	 * Returns the action note of this process order.
	 *
	 * @return the action note of this process order
	 */
	@AutoEscape
	public String getActionNote();

	/**
	 * Sets the action note of this process order.
	 *
	 * @param actionNote the action note of this process order
	 */
	public void setActionNote(String actionNote);

	/**
	 * Returns the assign to user ID of this process order.
	 *
	 * @return the assign to user ID of this process order
	 */
	public long getAssignToUserId();

	/**
	 * Sets the assign to user ID of this process order.
	 *
	 * @param assignToUserId the assign to user ID of this process order
	 */
	public void setAssignToUserId(long assignToUserId);

	/**
	 * Returns the assign to user uuid of this process order.
	 *
	 * @return the assign to user uuid of this process order
	 * @throws SystemException if a system exception occurred
	 */
	public String getAssignToUserUuid() throws SystemException;

	/**
	 * Sets the assign to user uuid of this process order.
	 *
	 * @param assignToUserUuid the assign to user uuid of this process order
	 */
	public void setAssignToUserUuid(String assignToUserUuid);

	/**
	 * Returns the process workflow ID of this process order.
	 *
	 * @return the process workflow ID of this process order
	 */
	public long getProcessWorkflowId();

	/**
	 * Sets the process workflow ID of this process order.
	 *
	 * @param processWorkflowId the process workflow ID of this process order
	 */
	public void setProcessWorkflowId(long processWorkflowId);

	/**
	 * Returns the dossier status of this process order.
	 *
	 * @return the dossier status of this process order
	 */
	@AutoEscape
	public String getDossierStatus();

	/**
	 * Sets the dossier status of this process order.
	 *
	 * @param dossierStatus the dossier status of this process order
	 */
	public void setDossierStatus(String dossierStatus);

	/**
	 * Returns the error info of this process order.
	 *
	 * @return the error info of this process order
	 */
	@AutoEscape
	public String getErrorInfo();

	/**
	 * Sets the error info of this process order.
	 *
	 * @param errorInfo the error info of this process order
	 */
	public void setErrorInfo(String errorInfo);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.opencps.processmgt.model.ProcessOrder processOrder);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.opencps.processmgt.model.ProcessOrder> toCacheModel();

	@Override
	public org.opencps.processmgt.model.ProcessOrder toEscapedModel();

	@Override
	public org.opencps.processmgt.model.ProcessOrder toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}