/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.opencps.processmgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ProcessStep service. Represents a row in the &quot;opencps_processstep&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.opencps.processmgt.model.impl.ProcessStepModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.opencps.processmgt.model.impl.ProcessStepImpl}.
 * </p>
 *
 * @author khoavd
 * @see ProcessStep
 * @see org.opencps.processmgt.model.impl.ProcessStepImpl
 * @see org.opencps.processmgt.model.impl.ProcessStepModelImpl
 * @generated
 */
public interface ProcessStepModel extends BaseModel<ProcessStep> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a process step model instance should use the {@link ProcessStep} interface instead.
	 */

	/**
	 * Returns the primary key of this process step.
	 *
	 * @return the primary key of this process step
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this process step.
	 *
	 * @param primaryKey the primary key of this process step
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the process step ID of this process step.
	 *
	 * @return the process step ID of this process step
	 */
	public long getProcessStepId();

	/**
	 * Sets the process step ID of this process step.
	 *
	 * @param processStepId the process step ID of this process step
	 */
	public void setProcessStepId(long processStepId);

	/**
	 * Returns the company ID of this process step.
	 *
	 * @return the company ID of this process step
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this process step.
	 *
	 * @param companyId the company ID of this process step
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this process step.
	 *
	 * @return the group ID of this process step
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this process step.
	 *
	 * @param groupId the group ID of this process step
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this process step.
	 *
	 * @return the user ID of this process step
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this process step.
	 *
	 * @param userId the user ID of this process step
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this process step.
	 *
	 * @return the user uuid of this process step
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this process step.
	 *
	 * @param userUuid the user uuid of this process step
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this process step.
	 *
	 * @return the create date of this process step
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this process step.
	 *
	 * @param createDate the create date of this process step
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this process step.
	 *
	 * @return the modified date of this process step
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this process step.
	 *
	 * @param modifiedDate the modified date of this process step
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the service process ID of this process step.
	 *
	 * @return the service process ID of this process step
	 */
	public long getServiceProcessId();

	/**
	 * Sets the service process ID of this process step.
	 *
	 * @param serviceProcessId the service process ID of this process step
	 */
	public void setServiceProcessId(long serviceProcessId);

	/**
	 * Returns the step name of this process step.
	 *
	 * @return the step name of this process step
	 */
	@AutoEscape
	public String getStepName();

	/**
	 * Sets the step name of this process step.
	 *
	 * @param stepName the step name of this process step
	 */
	public void setStepName(String stepName);

	/**
	 * Returns the sequence no of this process step.
	 *
	 * @return the sequence no of this process step
	 */
	public int getSequenceNo();

	/**
	 * Sets the sequence no of this process step.
	 *
	 * @param sequenceNo the sequence no of this process step
	 */
	public void setSequenceNo(int sequenceNo);

	/**
	 * Returns the dossier status of this process step.
	 *
	 * @return the dossier status of this process step
	 */
	@AutoEscape
	public String getDossierStatus();

	/**
	 * Sets the dossier status of this process step.
	 *
	 * @param dossierStatus the dossier status of this process step
	 */
	public void setDossierStatus(String dossierStatus);

	/**
	 * Returns the days duration of this process step.
	 *
	 * @return the days duration of this process step
	 */
	public int getDaysDuration();

	/**
	 * Sets the days duration of this process step.
	 *
	 * @param daysDuration the days duration of this process step
	 */
	public void setDaysDuration(int daysDuration);

	/**
	 * Returns the reference dossier part ID of this process step.
	 *
	 * @return the reference dossier part ID of this process step
	 */
	public long getReferenceDossierPartId();

	/**
	 * Sets the reference dossier part ID of this process step.
	 *
	 * @param referenceDossierPartId the reference dossier part ID of this process step
	 */
	public void setReferenceDossierPartId(long referenceDossierPartId);

	/**
	 * Returns the external app url of this process step.
	 *
	 * @return the external app url of this process step
	 */
	@AutoEscape
	public String getExternalAppUrl();

	/**
	 * Sets the external app url of this process step.
	 *
	 * @param externalAppUrl the external app url of this process step
	 */
	public void setExternalAppUrl(String externalAppUrl);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.opencps.processmgt.model.ProcessStep processStep);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.opencps.processmgt.model.ProcessStep> toCacheModel();

	@Override
	public org.opencps.processmgt.model.ProcessStep toEscapedModel();

	@Override
	public org.opencps.processmgt.model.ProcessStep toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}