/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.opencps.processmgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SchedulerJobs service. Represents a row in the &quot;opencps_scheduler_jobs&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.opencps.processmgt.model.impl.SchedulerJobsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.opencps.processmgt.model.impl.SchedulerJobsImpl}.
 * </p>
 *
 * @author khoavd
 * @see SchedulerJobs
 * @see org.opencps.processmgt.model.impl.SchedulerJobsImpl
 * @see org.opencps.processmgt.model.impl.SchedulerJobsModelImpl
 * @generated
 */
public interface SchedulerJobsModel extends BaseModel<SchedulerJobs> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a scheduler jobs model instance should use the {@link SchedulerJobs} interface instead.
	 */

	/**
	 * Returns the primary key of this scheduler jobs.
	 *
	 * @return the primary key of this scheduler jobs
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this scheduler jobs.
	 *
	 * @param primaryKey the primary key of this scheduler jobs
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the scheduler jobs ID of this scheduler jobs.
	 *
	 * @return the scheduler jobs ID of this scheduler jobs
	 */
	public long getSchedulerJobsId();

	/**
	 * Sets the scheduler jobs ID of this scheduler jobs.
	 *
	 * @param schedulerJobsId the scheduler jobs ID of this scheduler jobs
	 */
	public void setSchedulerJobsId(long schedulerJobsId);

	/**
	 * Returns the create date of this scheduler jobs.
	 *
	 * @return the create date of this scheduler jobs
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this scheduler jobs.
	 *
	 * @param createDate the create date of this scheduler jobs
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this scheduler jobs.
	 *
	 * @return the modified date of this scheduler jobs
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this scheduler jobs.
	 *
	 * @param modifiedDate the modified date of this scheduler jobs
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the dossier ID of this scheduler jobs.
	 *
	 * @return the dossier ID of this scheduler jobs
	 */
	public long getDossierId();

	/**
	 * Sets the dossier ID of this scheduler jobs.
	 *
	 * @param dossierId the dossier ID of this scheduler jobs
	 */
	public void setDossierId(long dossierId);

	/**
	 * Returns the file group ID of this scheduler jobs.
	 *
	 * @return the file group ID of this scheduler jobs
	 */
	public long getFileGroupId();

	/**
	 * Sets the file group ID of this scheduler jobs.
	 *
	 * @param fileGroupId the file group ID of this scheduler jobs
	 */
	public void setFileGroupId(long fileGroupId);

	/**
	 * Returns the process workflow ID of this scheduler jobs.
	 *
	 * @return the process workflow ID of this scheduler jobs
	 */
	public long getProcessWorkflowId();

	/**
	 * Sets the process workflow ID of this scheduler jobs.
	 *
	 * @param processWorkflowId the process workflow ID of this scheduler jobs
	 */
	public void setProcessWorkflowId(long processWorkflowId);

	/**
	 * Returns the scheduler type of this scheduler jobs.
	 *
	 * @return the scheduler type of this scheduler jobs
	 */
	public int getSchedulerType();

	/**
	 * Sets the scheduler type of this scheduler jobs.
	 *
	 * @param schedulerType the scheduler type of this scheduler jobs
	 */
	public void setSchedulerType(int schedulerType);

	/**
	 * Returns the sheduler pattern of this scheduler jobs.
	 *
	 * @return the sheduler pattern of this scheduler jobs
	 */
	@AutoEscape
	public String getShedulerPattern();

	/**
	 * Sets the sheduler pattern of this scheduler jobs.
	 *
	 * @param shedulerPattern the sheduler pattern of this scheduler jobs
	 */
	public void setShedulerPattern(String shedulerPattern);

	/**
	 * Returns the status of this scheduler jobs.
	 *
	 * @return the status of this scheduler jobs
	 */
	public int getStatus();

	/**
	 * Sets the status of this scheduler jobs.
	 *
	 * @param status the status of this scheduler jobs
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.opencps.processmgt.model.SchedulerJobs schedulerJobs);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.opencps.processmgt.model.SchedulerJobs> toCacheModel();

	@Override
	public org.opencps.processmgt.model.SchedulerJobs toEscapedModel();

	@Override
	public org.opencps.processmgt.model.SchedulerJobs toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}