/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.opencps.processmgt.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the StepAllowance service. Represents a row in the &quot;opencps_stepallowance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.opencps.processmgt.model.impl.StepAllowanceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.opencps.processmgt.model.impl.StepAllowanceImpl}.
 * </p>
 *
 * @author khoavd
 * @see StepAllowance
 * @see org.opencps.processmgt.model.impl.StepAllowanceImpl
 * @see org.opencps.processmgt.model.impl.StepAllowanceModelImpl
 * @generated
 */
public interface StepAllowanceModel extends BaseModel<StepAllowance> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a step allowance model instance should use the {@link StepAllowance} interface instead.
	 */

	/**
	 * Returns the primary key of this step allowance.
	 *
	 * @return the primary key of this step allowance
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this step allowance.
	 *
	 * @param primaryKey the primary key of this step allowance
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the step allowance ID of this step allowance.
	 *
	 * @return the step allowance ID of this step allowance
	 */
	public long getStepAllowanceId();

	/**
	 * Sets the step allowance ID of this step allowance.
	 *
	 * @param stepAllowanceId the step allowance ID of this step allowance
	 */
	public void setStepAllowanceId(long stepAllowanceId);

	/**
	 * Returns the process step ID of this step allowance.
	 *
	 * @return the process step ID of this step allowance
	 */
	public long getProcessStepId();

	/**
	 * Sets the process step ID of this step allowance.
	 *
	 * @param processStepId the process step ID of this step allowance
	 */
	public void setProcessStepId(long processStepId);

	/**
	 * Returns the role ID of this step allowance.
	 *
	 * @return the role ID of this step allowance
	 */
	public long getRoleId();

	/**
	 * Sets the role ID of this step allowance.
	 *
	 * @param roleId the role ID of this step allowance
	 */
	public void setRoleId(long roleId);

	/**
	 * Returns the read only of this step allowance.
	 *
	 * @return the read only of this step allowance
	 */
	public boolean getReadOnly();

	/**
	 * Returns <code>true</code> if this step allowance is read only.
	 *
	 * @return <code>true</code> if this step allowance is read only; <code>false</code> otherwise
	 */
	public boolean isReadOnly();

	/**
	 * Sets whether this step allowance is read only.
	 *
	 * @param readOnly the read only of this step allowance
	 */
	public void setReadOnly(boolean readOnly);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.opencps.processmgt.model.StepAllowance stepAllowance);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.opencps.processmgt.model.StepAllowance> toCacheModel();

	@Override
	public org.opencps.processmgt.model.StepAllowance toEscapedModel();

	@Override
	public org.opencps.processmgt.model.StepAllowance toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}