/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.opencps.paymentmgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PaymentConfig service. Represents a row in the &quot;opencps_payment_config&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.opencps.paymentmgt.model.impl.PaymentConfigModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.opencps.paymentmgt.model.impl.PaymentConfigImpl}.
 * </p>
 *
 * @author trungdk
 * @see PaymentConfig
 * @see org.opencps.paymentmgt.model.impl.PaymentConfigImpl
 * @see org.opencps.paymentmgt.model.impl.PaymentConfigModelImpl
 * @generated
 */
public interface PaymentConfigModel extends BaseModel<PaymentConfig> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a Payment configuration model instance should use the {@link PaymentConfig} interface instead.
	 */

	/**
	 * Returns the primary key of this Payment configuration.
	 *
	 * @return the primary key of this Payment configuration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this Payment configuration.
	 *
	 * @param primaryKey the primary key of this Payment configuration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the payment config ID of this Payment configuration.
	 *
	 * @return the payment config ID of this Payment configuration
	 */
	public long getPaymentConfigId();

	/**
	 * Sets the payment config ID of this Payment configuration.
	 *
	 * @param paymentConfigId the payment config ID of this Payment configuration
	 */
	public void setPaymentConfigId(long paymentConfigId);

	/**
	 * Returns the company ID of this Payment configuration.
	 *
	 * @return the company ID of this Payment configuration
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this Payment configuration.
	 *
	 * @param companyId the company ID of this Payment configuration
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this Payment configuration.
	 *
	 * @return the group ID of this Payment configuration
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this Payment configuration.
	 *
	 * @param groupId the group ID of this Payment configuration
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this Payment configuration.
	 *
	 * @return the user ID of this Payment configuration
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this Payment configuration.
	 *
	 * @param userId the user ID of this Payment configuration
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this Payment configuration.
	 *
	 * @return the user uuid of this Payment configuration
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this Payment configuration.
	 *
	 * @param userUuid the user uuid of this Payment configuration
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this Payment configuration.
	 *
	 * @return the create date of this Payment configuration
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this Payment configuration.
	 *
	 * @param createDate the create date of this Payment configuration
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this Payment configuration.
	 *
	 * @return the modified date of this Payment configuration
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this Payment configuration.
	 *
	 * @param modifiedDate the modified date of this Payment configuration
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the gov agency organization ID of this Payment configuration.
	 *
	 * @return the gov agency organization ID of this Payment configuration
	 */
	public long getGovAgencyOrganizationId();

	/**
	 * Sets the gov agency organization ID of this Payment configuration.
	 *
	 * @param govAgencyOrganizationId the gov agency organization ID of this Payment configuration
	 */
	public void setGovAgencyOrganizationId(long govAgencyOrganizationId);

	/**
	 * Returns the gov agency name of this Payment configuration.
	 *
	 * @return the gov agency name of this Payment configuration
	 */
	@AutoEscape
	public String getGovAgencyName();

	/**
	 * Sets the gov agency name of this Payment configuration.
	 *
	 * @param govAgencyName the gov agency name of this Payment configuration
	 */
	public void setGovAgencyName(String govAgencyName);

	/**
	 * Returns the gov agency tax no of this Payment configuration.
	 *
	 * @return the gov agency tax no of this Payment configuration
	 */
	@AutoEscape
	public String getGovAgencyTaxNo();

	/**
	 * Sets the gov agency tax no of this Payment configuration.
	 *
	 * @param govAgencyTaxNo the gov agency tax no of this Payment configuration
	 */
	public void setGovAgencyTaxNo(String govAgencyTaxNo);

	/**
	 * Returns the invoice template no of this Payment configuration.
	 *
	 * @return the invoice template no of this Payment configuration
	 */
	@AutoEscape
	public String getInvoiceTemplateNo();

	/**
	 * Sets the invoice template no of this Payment configuration.
	 *
	 * @param invoiceTemplateNo the invoice template no of this Payment configuration
	 */
	public void setInvoiceTemplateNo(String invoiceTemplateNo);

	/**
	 * Returns the invoice issue no of this Payment configuration.
	 *
	 * @return the invoice issue no of this Payment configuration
	 */
	@AutoEscape
	public String getInvoiceIssueNo();

	/**
	 * Sets the invoice issue no of this Payment configuration.
	 *
	 * @param invoiceIssueNo the invoice issue no of this Payment configuration
	 */
	public void setInvoiceIssueNo(String invoiceIssueNo);

	/**
	 * Returns the invoice last no of this Payment configuration.
	 *
	 * @return the invoice last no of this Payment configuration
	 */
	@AutoEscape
	public String getInvoiceLastNo();

	/**
	 * Sets the invoice last no of this Payment configuration.
	 *
	 * @param invoiceLastNo the invoice last no of this Payment configuration
	 */
	public void setInvoiceLastNo(String invoiceLastNo);

	/**
	 * Returns the bank info of this Payment configuration.
	 *
	 * @return the bank info of this Payment configuration
	 */
	@AutoEscape
	public String getBankInfo();

	/**
	 * Sets the bank info of this Payment configuration.
	 *
	 * @param bankInfo the bank info of this Payment configuration
	 */
	public void setBankInfo(String bankInfo);

	/**
	 * Returns the place info of this Payment configuration.
	 *
	 * @return the place info of this Payment configuration
	 */
	@AutoEscape
	public String getPlaceInfo();

	/**
	 * Sets the place info of this Payment configuration.
	 *
	 * @param placeInfo the place info of this Payment configuration
	 */
	public void setPlaceInfo(String placeInfo);

	/**
	 * Returns the keypay domain of this Payment configuration.
	 *
	 * @return the keypay domain of this Payment configuration
	 */
	@AutoEscape
	public String getKeypayDomain();

	/**
	 * Sets the keypay domain of this Payment configuration.
	 *
	 * @param keypayDomain the keypay domain of this Payment configuration
	 */
	public void setKeypayDomain(String keypayDomain);

	/**
	 * Returns the keypay version of this Payment configuration.
	 *
	 * @return the keypay version of this Payment configuration
	 */
	@AutoEscape
	public String getKeypayVersion();

	/**
	 * Sets the keypay version of this Payment configuration.
	 *
	 * @param keypayVersion the keypay version of this Payment configuration
	 */
	public void setKeypayVersion(String keypayVersion);

	/**
	 * Returns the keypay merchant code of this Payment configuration.
	 *
	 * @return the keypay merchant code of this Payment configuration
	 */
	@AutoEscape
	public String getKeypayMerchantCode();

	/**
	 * Sets the keypay merchant code of this Payment configuration.
	 *
	 * @param keypayMerchantCode the keypay merchant code of this Payment configuration
	 */
	public void setKeypayMerchantCode(String keypayMerchantCode);

	/**
	 * Returns the keypay secure key of this Payment configuration.
	 *
	 * @return the keypay secure key of this Payment configuration
	 */
	@AutoEscape
	public String getKeypaySecureKey();

	/**
	 * Sets the keypay secure key of this Payment configuration.
	 *
	 * @param keypaySecureKey the keypay secure key of this Payment configuration
	 */
	public void setKeypaySecureKey(String keypaySecureKey);

	/**
	 * Returns the report template of this Payment configuration.
	 *
	 * @return the report template of this Payment configuration
	 */
	@AutoEscape
	public String getReportTemplate();

	/**
	 * Sets the report template of this Payment configuration.
	 *
	 * @param reportTemplate the report template of this Payment configuration
	 */
	public void setReportTemplate(String reportTemplate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.opencps.paymentmgt.model.PaymentConfig paymentConfig);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.opencps.paymentmgt.model.PaymentConfig> toCacheModel();

	@Override
	public org.opencps.paymentmgt.model.PaymentConfig toEscapedModel();

	@Override
	public org.opencps.paymentmgt.model.PaymentConfig toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}