/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.opencps.servicemgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ServiceInfo service. Represents a row in the &quot;opencps_serviceinfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.opencps.servicemgt.model.impl.ServiceInfoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.opencps.servicemgt.model.impl.ServiceInfoImpl}.
 * </p>
 *
 * @author khoavd
 * @see ServiceInfo
 * @see org.opencps.servicemgt.model.impl.ServiceInfoImpl
 * @see org.opencps.servicemgt.model.impl.ServiceInfoModelImpl
 * @generated
 */
public interface ServiceInfoModel extends BaseModel<ServiceInfo>, StagedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a service info model instance should use the {@link ServiceInfo} interface instead.
	 */

	/**
	 * Returns the primary key of this service info.
	 *
	 * @return the primary key of this service info
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this service info.
	 *
	 * @param primaryKey the primary key of this service info
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this service info.
	 *
	 * @return the uuid of this service info
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this service info.
	 *
	 * @param uuid the uuid of this service info
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the serviceinfo ID of this service info.
	 *
	 * @return the serviceinfo ID of this service info
	 */
	public long getServiceinfoId();

	/**
	 * Sets the serviceinfo ID of this service info.
	 *
	 * @param serviceinfoId the serviceinfo ID of this service info
	 */
	public void setServiceinfoId(long serviceinfoId);

	/**
	 * Returns the company ID of this service info.
	 *
	 * @return the company ID of this service info
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this service info.
	 *
	 * @param companyId the company ID of this service info
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this service info.
	 *
	 * @return the group ID of this service info
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this service info.
	 *
	 * @param groupId the group ID of this service info
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this service info.
	 *
	 * @return the user ID of this service info
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this service info.
	 *
	 * @param userId the user ID of this service info
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this service info.
	 *
	 * @return the user uuid of this service info
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this service info.
	 *
	 * @param userUuid the user uuid of this service info
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this service info.
	 *
	 * @return the create date of this service info
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this service info.
	 *
	 * @param createDate the create date of this service info
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this service info.
	 *
	 * @return the modified date of this service info
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this service info.
	 *
	 * @param modifiedDate the modified date of this service info
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the service no of this service info.
	 *
	 * @return the service no of this service info
	 */
	@AutoEscape
	public String getServiceNo();

	/**
	 * Sets the service no of this service info.
	 *
	 * @param serviceNo the service no of this service info
	 */
	public void setServiceNo(String serviceNo);

	/**
	 * Returns the service name of this service info.
	 *
	 * @return the service name of this service info
	 */
	@AutoEscape
	public String getServiceName();

	/**
	 * Sets the service name of this service info.
	 *
	 * @param serviceName the service name of this service info
	 */
	public void setServiceName(String serviceName);

	/**
	 * Returns the full name of this service info.
	 *
	 * @return the full name of this service info
	 */
	@AutoEscape
	public String getFullName();

	/**
	 * Sets the full name of this service info.
	 *
	 * @param fullName the full name of this service info
	 */
	public void setFullName(String fullName);

	/**
	 * Returns the service process of this service info.
	 *
	 * @return the service process of this service info
	 */
	@AutoEscape
	public String getServiceProcess();

	/**
	 * Sets the service process of this service info.
	 *
	 * @param serviceProcess the service process of this service info
	 */
	public void setServiceProcess(String serviceProcess);

	/**
	 * Returns the service method of this service info.
	 *
	 * @return the service method of this service info
	 */
	@AutoEscape
	public String getServiceMethod();

	/**
	 * Sets the service method of this service info.
	 *
	 * @param serviceMethod the service method of this service info
	 */
	public void setServiceMethod(String serviceMethod);

	/**
	 * Returns the service dossier of this service info.
	 *
	 * @return the service dossier of this service info
	 */
	@AutoEscape
	public String getServiceDossier();

	/**
	 * Sets the service dossier of this service info.
	 *
	 * @param serviceDossier the service dossier of this service info
	 */
	public void setServiceDossier(String serviceDossier);

	/**
	 * Returns the service condition of this service info.
	 *
	 * @return the service condition of this service info
	 */
	@AutoEscape
	public String getServiceCondition();

	/**
	 * Sets the service condition of this service info.
	 *
	 * @param serviceCondition the service condition of this service info
	 */
	public void setServiceCondition(String serviceCondition);

	/**
	 * Returns the service duration of this service info.
	 *
	 * @return the service duration of this service info
	 */
	@AutoEscape
	public String getServiceDuration();

	/**
	 * Sets the service duration of this service info.
	 *
	 * @param serviceDuration the service duration of this service info
	 */
	public void setServiceDuration(String serviceDuration);

	/**
	 * Returns the service actors of this service info.
	 *
	 * @return the service actors of this service info
	 */
	@AutoEscape
	public String getServiceActors();

	/**
	 * Sets the service actors of this service info.
	 *
	 * @param serviceActors the service actors of this service info
	 */
	public void setServiceActors(String serviceActors);

	/**
	 * Returns the service results of this service info.
	 *
	 * @return the service results of this service info
	 */
	@AutoEscape
	public String getServiceResults();

	/**
	 * Sets the service results of this service info.
	 *
	 * @param serviceResults the service results of this service info
	 */
	public void setServiceResults(String serviceResults);

	/**
	 * Returns the service records of this service info.
	 *
	 * @return the service records of this service info
	 */
	@AutoEscape
	public String getServiceRecords();

	/**
	 * Sets the service records of this service info.
	 *
	 * @param serviceRecords the service records of this service info
	 */
	public void setServiceRecords(String serviceRecords);

	/**
	 * Returns the service fee of this service info.
	 *
	 * @return the service fee of this service info
	 */
	@AutoEscape
	public String getServiceFee();

	/**
	 * Sets the service fee of this service info.
	 *
	 * @param serviceFee the service fee of this service info
	 */
	public void setServiceFee(String serviceFee);

	/**
	 * Returns the service instructions of this service info.
	 *
	 * @return the service instructions of this service info
	 */
	@AutoEscape
	public String getServiceInstructions();

	/**
	 * Sets the service instructions of this service info.
	 *
	 * @param serviceInstructions the service instructions of this service info
	 */
	public void setServiceInstructions(String serviceInstructions);

	/**
	 * Returns the administration code of this service info.
	 *
	 * @return the administration code of this service info
	 */
	@AutoEscape
	public String getAdministrationCode();

	/**
	 * Sets the administration code of this service info.
	 *
	 * @param administrationCode the administration code of this service info
	 */
	public void setAdministrationCode(String administrationCode);

	/**
	 * Returns the administration index of this service info.
	 *
	 * @return the administration index of this service info
	 */
	@AutoEscape
	public String getAdministrationIndex();

	/**
	 * Sets the administration index of this service info.
	 *
	 * @param administrationIndex the administration index of this service info
	 */
	public void setAdministrationIndex(String administrationIndex);

	/**
	 * Returns the domain code of this service info.
	 *
	 * @return the domain code of this service info
	 */
	@AutoEscape
	public String getDomainCode();

	/**
	 * Sets the domain code of this service info.
	 *
	 * @param domainCode the domain code of this service info
	 */
	public void setDomainCode(String domainCode);

	/**
	 * Returns the domain index of this service info.
	 *
	 * @return the domain index of this service info
	 */
	@AutoEscape
	public String getDomainIndex();

	/**
	 * Sets the domain index of this service info.
	 *
	 * @param domainIndex the domain index of this service info
	 */
	public void setDomainIndex(String domainIndex);

	/**
	 * Returns the active status of this service info.
	 *
	 * @return the active status of this service info
	 */
	public int getActiveStatus();

	/**
	 * Sets the active status of this service info.
	 *
	 * @param activeStatus the active status of this service info
	 */
	public void setActiveStatus(int activeStatus);

	/**
	 * Returns the has template files of this service info.
	 *
	 * @return the has template files of this service info
	 */
	public int getHasTemplateFiles();

	/**
	 * Sets the has template files of this service info.
	 *
	 * @param hasTemplateFiles the has template files of this service info
	 */
	public void setHasTemplateFiles(int hasTemplateFiles);

	/**
	 * Returns the online url of this service info.
	 *
	 * @return the online url of this service info
	 */
	@AutoEscape
	public String getOnlineUrl();

	/**
	 * Sets the online url of this service info.
	 *
	 * @param onlineUrl the online url of this service info
	 */
	public void setOnlineUrl(String onlineUrl);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.opencps.servicemgt.model.ServiceInfo serviceInfo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.opencps.servicemgt.model.ServiceInfo> toCacheModel();

	@Override
	public org.opencps.servicemgt.model.ServiceInfo toEscapedModel();

	@Override
	public org.opencps.servicemgt.model.ServiceInfo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}