/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.opencps.servicemgt.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import org.opencps.servicemgt.service.persistence.ServiceFileTemplatePK;

import java.io.Serializable;

/**
 * The base model interface for the ServiceFileTemplate service. Represents a row in the &quot;opencps_service_templatefile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.opencps.servicemgt.model.impl.ServiceFileTemplateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.opencps.servicemgt.model.impl.ServiceFileTemplateImpl}.
 * </p>
 *
 * @author khoavd
 * @see ServiceFileTemplate
 * @see org.opencps.servicemgt.model.impl.ServiceFileTemplateImpl
 * @see org.opencps.servicemgt.model.impl.ServiceFileTemplateModelImpl
 * @generated
 */
public interface ServiceFileTemplateModel extends BaseModel<ServiceFileTemplate> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a service file template model instance should use the {@link ServiceFileTemplate} interface instead.
	 */

	/**
	 * Returns the primary key of this service file template.
	 *
	 * @return the primary key of this service file template
	 */
	public ServiceFileTemplatePK getPrimaryKey();

	/**
	 * Sets the primary key of this service file template.
	 *
	 * @param primaryKey the primary key of this service file template
	 */
	public void setPrimaryKey(ServiceFileTemplatePK primaryKey);

	/**
	 * Returns the serviceinfo ID of this service file template.
	 *
	 * @return the serviceinfo ID of this service file template
	 */
	public long getServiceinfoId();

	/**
	 * Sets the serviceinfo ID of this service file template.
	 *
	 * @param serviceinfoId the serviceinfo ID of this service file template
	 */
	public void setServiceinfoId(long serviceinfoId);

	/**
	 * Returns the templatefile ID of this service file template.
	 *
	 * @return the templatefile ID of this service file template
	 */
	public long getTemplatefileId();

	/**
	 * Sets the templatefile ID of this service file template.
	 *
	 * @param templatefileId the templatefile ID of this service file template
	 */
	public void setTemplatefileId(long templatefileId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.opencps.servicemgt.model.ServiceFileTemplate serviceFileTemplate);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.opencps.servicemgt.model.ServiceFileTemplate> toCacheModel();

	@Override
	public org.opencps.servicemgt.model.ServiceFileTemplate toEscapedModel();

	@Override
	public org.opencps.servicemgt.model.ServiceFileTemplate toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}