/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.opencps.accountmgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BusinessAccount service. Represents a row in the &quot;opencps_acc_business_account&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.opencps.accountmgt.model.impl.BusinessAccountModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.opencps.accountmgt.model.impl.BusinessAccountImpl}.
 * </p>
 *
 * @author khoavd
 * @see BusinessAccount
 * @see org.opencps.accountmgt.model.impl.BusinessAccountImpl
 * @see org.opencps.accountmgt.model.impl.BusinessAccountModelImpl
 * @generated
 */
public interface BusinessAccountModel extends BaseModel<BusinessAccount> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a business account model instance should use the {@link BusinessAccount} interface instead.
	 */

	/**
	 * Returns the primary key of this business account.
	 *
	 * @return the primary key of this business account
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this business account.
	 *
	 * @param primaryKey the primary key of this business account
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the business account ID of this business account.
	 *
	 * @return the business account ID of this business account
	 */
	public long getBusinessAccountId();

	/**
	 * Sets the business account ID of this business account.
	 *
	 * @param businessAccountId the business account ID of this business account
	 */
	public void setBusinessAccountId(long businessAccountId);

	/**
	 * Returns the company ID of this business account.
	 *
	 * @return the company ID of this business account
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this business account.
	 *
	 * @param companyId the company ID of this business account
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this business account.
	 *
	 * @return the group ID of this business account
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this business account.
	 *
	 * @param groupId the group ID of this business account
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this business account.
	 *
	 * @return the user ID of this business account
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this business account.
	 *
	 * @param userId the user ID of this business account
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this business account.
	 *
	 * @return the user uuid of this business account
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this business account.
	 *
	 * @param userUuid the user uuid of this business account
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this business account.
	 *
	 * @return the create date of this business account
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this business account.
	 *
	 * @param createDate the create date of this business account
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this business account.
	 *
	 * @return the modified date of this business account
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this business account.
	 *
	 * @param modifiedDate the modified date of this business account
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the business ID of this business account.
	 *
	 * @return the business ID of this business account
	 */
	public long getBusinessId();

	/**
	 * Sets the business ID of this business account.
	 *
	 * @param businessId the business ID of this business account
	 */
	public void setBusinessId(long businessId);

	/**
	 * Returns the full name of this business account.
	 *
	 * @return the full name of this business account
	 */
	@AutoEscape
	public String getFullName();

	/**
	 * Sets the full name of this business account.
	 *
	 * @param fullName the full name of this business account
	 */
	public void setFullName(String fullName);

	/**
	 * Returns the working role of this business account.
	 *
	 * @return the working role of this business account
	 */
	@AutoEscape
	public String getWorkingRole();

	/**
	 * Sets the working role of this business account.
	 *
	 * @param workingRole the working role of this business account
	 */
	public void setWorkingRole(String workingRole);

	/**
	 * Returns the tel no of this business account.
	 *
	 * @return the tel no of this business account
	 */
	@AutoEscape
	public String getTelNo();

	/**
	 * Sets the tel no of this business account.
	 *
	 * @param telNo the tel no of this business account
	 */
	public void setTelNo(String telNo);

	/**
	 * Returns the email of this business account.
	 *
	 * @return the email of this business account
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this business account.
	 *
	 * @param email the email of this business account
	 */
	public void setEmail(String email);

	/**
	 * Returns the mapping user ID of this business account.
	 *
	 * @return the mapping user ID of this business account
	 */
	public long getMappingUserId();

	/**
	 * Sets the mapping user ID of this business account.
	 *
	 * @param mappingUserId the mapping user ID of this business account
	 */
	public void setMappingUserId(long mappingUserId);

	/**
	 * Returns the mapping user uuid of this business account.
	 *
	 * @return the mapping user uuid of this business account
	 * @throws SystemException if a system exception occurred
	 */
	public String getMappingUserUuid() throws SystemException;

	/**
	 * Sets the mapping user uuid of this business account.
	 *
	 * @param mappingUserUuid the mapping user uuid of this business account
	 */
	public void setMappingUserUuid(String mappingUserUuid);

	/**
	 * Returns the has permissions of this business account.
	 *
	 * @return the has permissions of this business account
	 */
	@AutoEscape
	public String getHasPermissions();

	/**
	 * Sets the has permissions of this business account.
	 *
	 * @param hasPermissions the has permissions of this business account
	 */
	public void setHasPermissions(String hasPermissions);

	/**
	 * Returns the account status of this business account.
	 *
	 * @return the account status of this business account
	 */
	public int getAccountStatus();

	/**
	 * Sets the account status of this business account.
	 *
	 * @param accountStatus the account status of this business account
	 */
	public void setAccountStatus(int accountStatus);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.opencps.accountmgt.model.BusinessAccount businessAccount);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.opencps.accountmgt.model.BusinessAccount> toCacheModel();

	@Override
	public org.opencps.accountmgt.model.BusinessAccount toEscapedModel();

	@Override
	public org.opencps.accountmgt.model.BusinessAccount toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}