/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.opencps.accountmgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Business service. Represents a row in the &quot;opencps_acc_business&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.opencps.accountmgt.model.impl.BusinessModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.opencps.accountmgt.model.impl.BusinessImpl}.
 * </p>
 *
 * @author khoavd
 * @see Business
 * @see org.opencps.accountmgt.model.impl.BusinessImpl
 * @see org.opencps.accountmgt.model.impl.BusinessModelImpl
 * @generated
 */
public interface BusinessModel extends BaseModel<Business> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a business model instance should use the {@link Business} interface instead.
	 */

	/**
	 * Returns the primary key of this business.
	 *
	 * @return the primary key of this business
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this business.
	 *
	 * @param primaryKey the primary key of this business
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the business ID of this business.
	 *
	 * @return the business ID of this business
	 */
	public long getBusinessId();

	/**
	 * Sets the business ID of this business.
	 *
	 * @param businessId the business ID of this business
	 */
	public void setBusinessId(long businessId);

	/**
	 * Returns the company ID of this business.
	 *
	 * @return the company ID of this business
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this business.
	 *
	 * @param companyId the company ID of this business
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this business.
	 *
	 * @return the group ID of this business
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this business.
	 *
	 * @param groupId the group ID of this business
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this business.
	 *
	 * @return the user ID of this business
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this business.
	 *
	 * @param userId the user ID of this business
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this business.
	 *
	 * @return the user uuid of this business
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this business.
	 *
	 * @param userUuid the user uuid of this business
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this business.
	 *
	 * @return the create date of this business
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this business.
	 *
	 * @param createDate the create date of this business
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this business.
	 *
	 * @return the modified date of this business
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this business.
	 *
	 * @param modifiedDate the modified date of this business
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the uuid of this business.
	 *
	 * @return the uuid of this business
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this business.
	 *
	 * @param uuid the uuid of this business
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the name of this business.
	 *
	 * @return the name of this business
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this business.
	 *
	 * @param name the name of this business
	 */
	public void setName(String name);

	/**
	 * Returns the en name of this business.
	 *
	 * @return the en name of this business
	 */
	@AutoEscape
	public String getEnName();

	/**
	 * Sets the en name of this business.
	 *
	 * @param enName the en name of this business
	 */
	public void setEnName(String enName);

	/**
	 * Returns the short name of this business.
	 *
	 * @return the short name of this business
	 */
	@AutoEscape
	public String getShortName();

	/**
	 * Sets the short name of this business.
	 *
	 * @param shortName the short name of this business
	 */
	public void setShortName(String shortName);

	/**
	 * Returns the business type of this business.
	 *
	 * @return the business type of this business
	 */
	@AutoEscape
	public String getBusinessType();

	/**
	 * Sets the business type of this business.
	 *
	 * @param businessType the business type of this business
	 */
	public void setBusinessType(String businessType);

	/**
	 * Returns the id number of this business.
	 *
	 * @return the id number of this business
	 */
	@AutoEscape
	public String getIdNumber();

	/**
	 * Sets the id number of this business.
	 *
	 * @param idNumber the id number of this business
	 */
	public void setIdNumber(String idNumber);

	/**
	 * Returns the address of this business.
	 *
	 * @return the address of this business
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this business.
	 *
	 * @param address the address of this business
	 */
	public void setAddress(String address);

	/**
	 * Returns the city code of this business.
	 *
	 * @return the city code of this business
	 */
	@AutoEscape
	public String getCityCode();

	/**
	 * Sets the city code of this business.
	 *
	 * @param cityCode the city code of this business
	 */
	public void setCityCode(String cityCode);

	/**
	 * Returns the district code of this business.
	 *
	 * @return the district code of this business
	 */
	@AutoEscape
	public String getDistrictCode();

	/**
	 * Sets the district code of this business.
	 *
	 * @param districtCode the district code of this business
	 */
	public void setDistrictCode(String districtCode);

	/**
	 * Returns the ward code of this business.
	 *
	 * @return the ward code of this business
	 */
	@AutoEscape
	public String getWardCode();

	/**
	 * Sets the ward code of this business.
	 *
	 * @param wardCode the ward code of this business
	 */
	public void setWardCode(String wardCode);

	/**
	 * Returns the tel no of this business.
	 *
	 * @return the tel no of this business
	 */
	@AutoEscape
	public String getTelNo();

	/**
	 * Sets the tel no of this business.
	 *
	 * @param telNo the tel no of this business
	 */
	public void setTelNo(String telNo);

	/**
	 * Returns the email of this business.
	 *
	 * @return the email of this business
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this business.
	 *
	 * @param email the email of this business
	 */
	public void setEmail(String email);

	/**
	 * Returns the representative name of this business.
	 *
	 * @return the representative name of this business
	 */
	@AutoEscape
	public String getRepresentativeName();

	/**
	 * Sets the representative name of this business.
	 *
	 * @param representativeName the representative name of this business
	 */
	public void setRepresentativeName(String representativeName);

	/**
	 * Returns the representative role of this business.
	 *
	 * @return the representative role of this business
	 */
	@AutoEscape
	public String getRepresentativeRole();

	/**
	 * Sets the representative role of this business.
	 *
	 * @param representativeRole the representative role of this business
	 */
	public void setRepresentativeRole(String representativeRole);

	/**
	 * Returns the attach file of this business.
	 *
	 * @return the attach file of this business
	 */
	public long getAttachFile();

	/**
	 * Sets the attach file of this business.
	 *
	 * @param attachFile the attach file of this business
	 */
	public void setAttachFile(long attachFile);

	/**
	 * Returns the mapping organization ID of this business.
	 *
	 * @return the mapping organization ID of this business
	 */
	public long getMappingOrganizationId();

	/**
	 * Sets the mapping organization ID of this business.
	 *
	 * @param mappingOrganizationId the mapping organization ID of this business
	 */
	public void setMappingOrganizationId(long mappingOrganizationId);

	/**
	 * Returns the mapping user ID of this business.
	 *
	 * @return the mapping user ID of this business
	 */
	public long getMappingUserId();

	/**
	 * Sets the mapping user ID of this business.
	 *
	 * @param mappingUserId the mapping user ID of this business
	 */
	public void setMappingUserId(long mappingUserId);

	/**
	 * Returns the mapping user uuid of this business.
	 *
	 * @return the mapping user uuid of this business
	 * @throws SystemException if a system exception occurred
	 */
	public String getMappingUserUuid() throws SystemException;

	/**
	 * Sets the mapping user uuid of this business.
	 *
	 * @param mappingUserUuid the mapping user uuid of this business
	 */
	public void setMappingUserUuid(String mappingUserUuid);

	/**
	 * Returns the account status of this business.
	 *
	 * @return the account status of this business
	 */
	public int getAccountStatus();

	/**
	 * Sets the account status of this business.
	 *
	 * @param accountStatus the account status of this business
	 */
	public void setAccountStatus(int accountStatus);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.opencps.accountmgt.model.Business business);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.opencps.accountmgt.model.Business> toCacheModel();

	@Override
	public org.opencps.accountmgt.model.Business toEscapedModel();

	@Override
	public org.opencps.accountmgt.model.Business toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}