/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.opencps.usermgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the WorkingUnit service. Represents a row in the &quot;opencps_workingunit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.opencps.usermgt.model.impl.WorkingUnitModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.opencps.usermgt.model.impl.WorkingUnitImpl}.
 * </p>
 *
 * @author khoavd
 * @see WorkingUnit
 * @see org.opencps.usermgt.model.impl.WorkingUnitImpl
 * @see org.opencps.usermgt.model.impl.WorkingUnitModelImpl
 * @generated
 */
public interface WorkingUnitModel extends BaseModel<WorkingUnit> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a working unit model instance should use the {@link WorkingUnit} interface instead.
	 */

	/**
	 * Returns the primary key of this working unit.
	 *
	 * @return the primary key of this working unit
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this working unit.
	 *
	 * @param primaryKey the primary key of this working unit
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the workingunit ID of this working unit.
	 *
	 * @return the workingunit ID of this working unit
	 */
	public long getWorkingunitId();

	/**
	 * Sets the workingunit ID of this working unit.
	 *
	 * @param workingunitId the workingunit ID of this working unit
	 */
	public void setWorkingunitId(long workingunitId);

	/**
	 * Returns the company ID of this working unit.
	 *
	 * @return the company ID of this working unit
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this working unit.
	 *
	 * @param companyId the company ID of this working unit
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this working unit.
	 *
	 * @return the group ID of this working unit
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this working unit.
	 *
	 * @param groupId the group ID of this working unit
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this working unit.
	 *
	 * @return the user ID of this working unit
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this working unit.
	 *
	 * @param userId the user ID of this working unit
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this working unit.
	 *
	 * @return the user uuid of this working unit
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this working unit.
	 *
	 * @param userUuid the user uuid of this working unit
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this working unit.
	 *
	 * @return the create date of this working unit
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this working unit.
	 *
	 * @param createDate the create date of this working unit
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this working unit.
	 *
	 * @return the modified date of this working unit
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this working unit.
	 *
	 * @param modifiedDate the modified date of this working unit
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this working unit.
	 *
	 * @return the name of this working unit
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this working unit.
	 *
	 * @param name the name of this working unit
	 */
	public void setName(String name);

	/**
	 * Returns the en name of this working unit.
	 *
	 * @return the en name of this working unit
	 */
	@AutoEscape
	public String getEnName();

	/**
	 * Sets the en name of this working unit.
	 *
	 * @param enName the en name of this working unit
	 */
	public void setEnName(String enName);

	/**
	 * Returns the gov agency code of this working unit.
	 *
	 * @return the gov agency code of this working unit
	 */
	@AutoEscape
	public String getGovAgencyCode();

	/**
	 * Sets the gov agency code of this working unit.
	 *
	 * @param govAgencyCode the gov agency code of this working unit
	 */
	public void setGovAgencyCode(String govAgencyCode);

	/**
	 * Returns the manager working unit ID of this working unit.
	 *
	 * @return the manager working unit ID of this working unit
	 */
	public long getManagerWorkingUnitId();

	/**
	 * Sets the manager working unit ID of this working unit.
	 *
	 * @param managerWorkingUnitId the manager working unit ID of this working unit
	 */
	public void setManagerWorkingUnitId(long managerWorkingUnitId);

	/**
	 * Returns the parent working unit ID of this working unit.
	 *
	 * @return the parent working unit ID of this working unit
	 */
	public long getParentWorkingUnitId();

	/**
	 * Sets the parent working unit ID of this working unit.
	 *
	 * @param parentWorkingUnitId the parent working unit ID of this working unit
	 */
	public void setParentWorkingUnitId(long parentWorkingUnitId);

	/**
	 * Returns the sibling of this working unit.
	 *
	 * @return the sibling of this working unit
	 */
	public int getSibling();

	/**
	 * Sets the sibling of this working unit.
	 *
	 * @param sibling the sibling of this working unit
	 */
	public void setSibling(int sibling);

	/**
	 * Returns the tree index of this working unit.
	 *
	 * @return the tree index of this working unit
	 */
	@AutoEscape
	public String getTreeIndex();

	/**
	 * Sets the tree index of this working unit.
	 *
	 * @param treeIndex the tree index of this working unit
	 */
	public void setTreeIndex(String treeIndex);

	/**
	 * Returns the address of this working unit.
	 *
	 * @return the address of this working unit
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this working unit.
	 *
	 * @param address the address of this working unit
	 */
	public void setAddress(String address);

	/**
	 * Returns the city code of this working unit.
	 *
	 * @return the city code of this working unit
	 */
	@AutoEscape
	public String getCityCode();

	/**
	 * Sets the city code of this working unit.
	 *
	 * @param cityCode the city code of this working unit
	 */
	public void setCityCode(String cityCode);

	/**
	 * Returns the district code of this working unit.
	 *
	 * @return the district code of this working unit
	 */
	@AutoEscape
	public String getDistrictCode();

	/**
	 * Sets the district code of this working unit.
	 *
	 * @param districtCode the district code of this working unit
	 */
	public void setDistrictCode(String districtCode);

	/**
	 * Returns the ward code of this working unit.
	 *
	 * @return the ward code of this working unit
	 */
	@AutoEscape
	public String getWardCode();

	/**
	 * Sets the ward code of this working unit.
	 *
	 * @param wardCode the ward code of this working unit
	 */
	public void setWardCode(String wardCode);

	/**
	 * Returns the tel no of this working unit.
	 *
	 * @return the tel no of this working unit
	 */
	@AutoEscape
	public String getTelNo();

	/**
	 * Sets the tel no of this working unit.
	 *
	 * @param telNo the tel no of this working unit
	 */
	public void setTelNo(String telNo);

	/**
	 * Returns the fax no of this working unit.
	 *
	 * @return the fax no of this working unit
	 */
	@AutoEscape
	public String getFaxNo();

	/**
	 * Sets the fax no of this working unit.
	 *
	 * @param faxNo the fax no of this working unit
	 */
	public void setFaxNo(String faxNo);

	/**
	 * Returns the email of this working unit.
	 *
	 * @return the email of this working unit
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this working unit.
	 *
	 * @param email the email of this working unit
	 */
	public void setEmail(String email);

	/**
	 * Returns the website of this working unit.
	 *
	 * @return the website of this working unit
	 */
	@AutoEscape
	public String getWebsite();

	/**
	 * Sets the website of this working unit.
	 *
	 * @param website the website of this working unit
	 */
	public void setWebsite(String website);

	/**
	 * Returns the is employer of this working unit.
	 *
	 * @return the is employer of this working unit
	 */
	public boolean getIsEmployer();

	/**
	 * Returns <code>true</code> if this working unit is is employer.
	 *
	 * @return <code>true</code> if this working unit is is employer; <code>false</code> otherwise
	 */
	public boolean isIsEmployer();

	/**
	 * Sets whether this working unit is is employer.
	 *
	 * @param isEmployer the is employer of this working unit
	 */
	public void setIsEmployer(boolean isEmployer);

	/**
	 * Returns the mapping organisation ID of this working unit.
	 *
	 * @return the mapping organisation ID of this working unit
	 */
	public long getMappingOrganisationId();

	/**
	 * Sets the mapping organisation ID of this working unit.
	 *
	 * @param mappingOrganisationId the mapping organisation ID of this working unit
	 */
	public void setMappingOrganisationId(long mappingOrganisationId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.opencps.usermgt.model.WorkingUnit workingUnit);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.opencps.usermgt.model.WorkingUnit> toCacheModel();

	@Override
	public org.opencps.usermgt.model.WorkingUnit toEscapedModel();

	@Override
	public org.opencps.usermgt.model.WorkingUnit toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}