/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.opencps.dossiermgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DossierFile service. Represents a row in the &quot;opencps_dossier_file&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.opencps.dossiermgt.model.impl.DossierFileModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.opencps.dossiermgt.model.impl.DossierFileImpl}.
 * </p>
 *
 * @author trungnt
 * @see DossierFile
 * @see org.opencps.dossiermgt.model.impl.DossierFileImpl
 * @see org.opencps.dossiermgt.model.impl.DossierFileModelImpl
 * @generated
 */
public interface DossierFileModel extends BaseModel<DossierFile> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dossier file model instance should use the {@link DossierFile} interface instead.
	 */

	/**
	 * Returns the primary key of this dossier file.
	 *
	 * @return the primary key of this dossier file
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dossier file.
	 *
	 * @param primaryKey the primary key of this dossier file
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dossier file ID of this dossier file.
	 *
	 * @return the dossier file ID of this dossier file
	 */
	public long getDossierFileId();

	/**
	 * Sets the dossier file ID of this dossier file.
	 *
	 * @param dossierFileId the dossier file ID of this dossier file
	 */
	public void setDossierFileId(long dossierFileId);

	/**
	 * Returns the company ID of this dossier file.
	 *
	 * @return the company ID of this dossier file
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this dossier file.
	 *
	 * @param companyId the company ID of this dossier file
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this dossier file.
	 *
	 * @return the group ID of this dossier file
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this dossier file.
	 *
	 * @param groupId the group ID of this dossier file
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this dossier file.
	 *
	 * @return the user ID of this dossier file
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this dossier file.
	 *
	 * @param userId the user ID of this dossier file
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dossier file.
	 *
	 * @return the user uuid of this dossier file
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this dossier file.
	 *
	 * @param userUuid the user uuid of this dossier file
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this dossier file.
	 *
	 * @return the create date of this dossier file
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this dossier file.
	 *
	 * @param createDate the create date of this dossier file
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this dossier file.
	 *
	 * @return the modified date of this dossier file
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dossier file.
	 *
	 * @param modifiedDate the modified date of this dossier file
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the dossier ID of this dossier file.
	 *
	 * @return the dossier ID of this dossier file
	 */
	public long getDossierId();

	/**
	 * Sets the dossier ID of this dossier file.
	 *
	 * @param dossierId the dossier ID of this dossier file
	 */
	public void setDossierId(long dossierId);

	/**
	 * Returns the oid of this dossier file.
	 *
	 * @return the oid of this dossier file
	 */
	@AutoEscape
	public String getOid();

	/**
	 * Sets the oid of this dossier file.
	 *
	 * @param oid the oid of this dossier file
	 */
	public void setOid(String oid);

	/**
	 * Returns the dossier part ID of this dossier file.
	 *
	 * @return the dossier part ID of this dossier file
	 */
	public long getDossierPartId();

	/**
	 * Sets the dossier part ID of this dossier file.
	 *
	 * @param dossierPartId the dossier part ID of this dossier file
	 */
	public void setDossierPartId(long dossierPartId);

	/**
	 * Returns the template file no of this dossier file.
	 *
	 * @return the template file no of this dossier file
	 */
	@AutoEscape
	public String getTemplateFileNo();

	/**
	 * Sets the template file no of this dossier file.
	 *
	 * @param templateFileNo the template file no of this dossier file
	 */
	public void setTemplateFileNo(String templateFileNo);

	/**
	 * Returns the group file ID of this dossier file.
	 *
	 * @return the group file ID of this dossier file
	 */
	public long getGroupFileId();

	/**
	 * Sets the group file ID of this dossier file.
	 *
	 * @param groupFileId the group file ID of this dossier file
	 */
	public void setGroupFileId(long groupFileId);

	/**
	 * Returns the owner user ID of this dossier file.
	 *
	 * @return the owner user ID of this dossier file
	 */
	public long getOwnerUserId();

	/**
	 * Sets the owner user ID of this dossier file.
	 *
	 * @param ownerUserId the owner user ID of this dossier file
	 */
	public void setOwnerUserId(long ownerUserId);

	/**
	 * Returns the owner user uuid of this dossier file.
	 *
	 * @return the owner user uuid of this dossier file
	 * @throws SystemException if a system exception occurred
	 */
	public String getOwnerUserUuid() throws SystemException;

	/**
	 * Sets the owner user uuid of this dossier file.
	 *
	 * @param ownerUserUuid the owner user uuid of this dossier file
	 */
	public void setOwnerUserUuid(String ownerUserUuid);

	/**
	 * Returns the owner organization ID of this dossier file.
	 *
	 * @return the owner organization ID of this dossier file
	 */
	public long getOwnerOrganizationId();

	/**
	 * Sets the owner organization ID of this dossier file.
	 *
	 * @param ownerOrganizationId the owner organization ID of this dossier file
	 */
	public void setOwnerOrganizationId(long ownerOrganizationId);

	/**
	 * Returns the gov agency organization ID of this dossier file.
	 *
	 * @return the gov agency organization ID of this dossier file
	 */
	public int getGovAgencyOrganizationId();

	/**
	 * Sets the gov agency organization ID of this dossier file.
	 *
	 * @param govAgencyOrganizationId the gov agency organization ID of this dossier file
	 */
	public void setGovAgencyOrganizationId(int govAgencyOrganizationId);

	/**
	 * Returns the display name of this dossier file.
	 *
	 * @return the display name of this dossier file
	 */
	@AutoEscape
	public String getDisplayName();

	/**
	 * Sets the display name of this dossier file.
	 *
	 * @param displayName the display name of this dossier file
	 */
	public void setDisplayName(String displayName);

	/**
	 * Returns the form data of this dossier file.
	 *
	 * @return the form data of this dossier file
	 */
	@AutoEscape
	public String getFormData();

	/**
	 * Sets the form data of this dossier file.
	 *
	 * @param formData the form data of this dossier file
	 */
	public void setFormData(String formData);

	/**
	 * Returns the file entry ID of this dossier file.
	 *
	 * @return the file entry ID of this dossier file
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this dossier file.
	 *
	 * @param fileEntryId the file entry ID of this dossier file
	 */
	public void setFileEntryId(long fileEntryId);

	/**
	 * Returns the dossier file mark of this dossier file.
	 *
	 * @return the dossier file mark of this dossier file
	 */
	public int getDossierFileMark();

	/**
	 * Sets the dossier file mark of this dossier file.
	 *
	 * @param dossierFileMark the dossier file mark of this dossier file
	 */
	public void setDossierFileMark(int dossierFileMark);

	/**
	 * Returns the dossier file type of this dossier file.
	 *
	 * @return the dossier file type of this dossier file
	 */
	public int getDossierFileType();

	/**
	 * Sets the dossier file type of this dossier file.
	 *
	 * @param dossierFileType the dossier file type of this dossier file
	 */
	public void setDossierFileType(int dossierFileType);

	/**
	 * Returns the dossier file no of this dossier file.
	 *
	 * @return the dossier file no of this dossier file
	 */
	@AutoEscape
	public String getDossierFileNo();

	/**
	 * Sets the dossier file no of this dossier file.
	 *
	 * @param dossierFileNo the dossier file no of this dossier file
	 */
	public void setDossierFileNo(String dossierFileNo);

	/**
	 * Returns the dossier file date of this dossier file.
	 *
	 * @return the dossier file date of this dossier file
	 */
	public Date getDossierFileDate();

	/**
	 * Sets the dossier file date of this dossier file.
	 *
	 * @param dossierFileDate the dossier file date of this dossier file
	 */
	public void setDossierFileDate(Date dossierFileDate);

	/**
	 * Returns the removed of this dossier file.
	 *
	 * @return the removed of this dossier file
	 */
	public int getRemoved();

	/**
	 * Sets the removed of this dossier file.
	 *
	 * @param removed the removed of this dossier file
	 */
	public void setRemoved(int removed);

	/**
	 * Returns the original of this dossier file.
	 *
	 * @return the original of this dossier file
	 */
	public int getOriginal();

	/**
	 * Sets the original of this dossier file.
	 *
	 * @param original the original of this dossier file
	 */
	public void setOriginal(int original);

	/**
	 * Returns the sync status of this dossier file.
	 *
	 * @return the sync status of this dossier file
	 */
	public int getSyncStatus();

	/**
	 * Sets the sync status of this dossier file.
	 *
	 * @param syncStatus the sync status of this dossier file
	 */
	public void setSyncStatus(int syncStatus);

	/**
	 * Returns the version of this dossier file.
	 *
	 * @return the version of this dossier file
	 */
	public int getVersion();

	/**
	 * Sets the version of this dossier file.
	 *
	 * @param version the version of this dossier file
	 */
	public void setVersion(int version);

	/**
	 * Returns the signed of this dossier file.
	 *
	 * @return the signed of this dossier file
	 */
	public boolean getSigned();

	/**
	 * Returns <code>true</code> if this dossier file is signed.
	 *
	 * @return <code>true</code> if this dossier file is signed; <code>false</code> otherwise
	 */
	public boolean isSigned();

	/**
	 * Sets whether this dossier file is signed.
	 *
	 * @param signed the signed of this dossier file
	 */
	public void setSigned(boolean signed);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.opencps.dossiermgt.model.DossierFile dossierFile);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.opencps.dossiermgt.model.DossierFile> toCacheModel();

	@Override
	public org.opencps.dossiermgt.model.DossierFile toEscapedModel();

	@Override
	public org.opencps.dossiermgt.model.DossierFile toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}