/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.opencps.dossiermgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Dossier service. Represents a row in the &quot;opencps_dossier&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.opencps.dossiermgt.model.impl.DossierModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.opencps.dossiermgt.model.impl.DossierImpl}.
 * </p>
 *
 * @author trungnt
 * @see Dossier
 * @see org.opencps.dossiermgt.model.impl.DossierImpl
 * @see org.opencps.dossiermgt.model.impl.DossierModelImpl
 * @generated
 */
public interface DossierModel extends BaseModel<Dossier> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dossier model instance should use the {@link Dossier} interface instead.
	 */

	/**
	 * Returns the primary key of this dossier.
	 *
	 * @return the primary key of this dossier
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dossier.
	 *
	 * @param primaryKey the primary key of this dossier
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dossier ID of this dossier.
	 *
	 * @return the dossier ID of this dossier
	 */
	public long getDossierId();

	/**
	 * Sets the dossier ID of this dossier.
	 *
	 * @param dossierId the dossier ID of this dossier
	 */
	public void setDossierId(long dossierId);

	/**
	 * Returns the company ID of this dossier.
	 *
	 * @return the company ID of this dossier
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this dossier.
	 *
	 * @param companyId the company ID of this dossier
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this dossier.
	 *
	 * @return the group ID of this dossier
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this dossier.
	 *
	 * @param groupId the group ID of this dossier
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this dossier.
	 *
	 * @return the user ID of this dossier
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this dossier.
	 *
	 * @param userId the user ID of this dossier
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dossier.
	 *
	 * @return the user uuid of this dossier
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this dossier.
	 *
	 * @param userUuid the user uuid of this dossier
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this dossier.
	 *
	 * @return the create date of this dossier
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this dossier.
	 *
	 * @param createDate the create date of this dossier
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this dossier.
	 *
	 * @return the modified date of this dossier
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dossier.
	 *
	 * @param modifiedDate the modified date of this dossier
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the oid of this dossier.
	 *
	 * @return the oid of this dossier
	 */
	@AutoEscape
	public String getOid();

	/**
	 * Sets the oid of this dossier.
	 *
	 * @param oid the oid of this dossier
	 */
	public void setOid(String oid);

	/**
	 * Returns the external ref no of this dossier.
	 *
	 * @return the external ref no of this dossier
	 */
	@AutoEscape
	public String getExternalRefNo();

	/**
	 * Sets the external ref no of this dossier.
	 *
	 * @param externalRefNo the external ref no of this dossier
	 */
	public void setExternalRefNo(String externalRefNo);

	/**
	 * Returns the external ref url of this dossier.
	 *
	 * @return the external ref url of this dossier
	 */
	@AutoEscape
	public String getExternalRefUrl();

	/**
	 * Sets the external ref url of this dossier.
	 *
	 * @param externalRefUrl the external ref url of this dossier
	 */
	public void setExternalRefUrl(String externalRefUrl);

	/**
	 * Returns the owner organization ID of this dossier.
	 *
	 * @return the owner organization ID of this dossier
	 */
	public long getOwnerOrganizationId();

	/**
	 * Sets the owner organization ID of this dossier.
	 *
	 * @param ownerOrganizationId the owner organization ID of this dossier
	 */
	public void setOwnerOrganizationId(long ownerOrganizationId);

	/**
	 * Returns the service config ID of this dossier.
	 *
	 * @return the service config ID of this dossier
	 */
	public long getServiceConfigId();

	/**
	 * Sets the service config ID of this dossier.
	 *
	 * @param serviceConfigId the service config ID of this dossier
	 */
	public void setServiceConfigId(long serviceConfigId);

	/**
	 * Returns the service info ID of this dossier.
	 *
	 * @return the service info ID of this dossier
	 */
	public long getServiceInfoId();

	/**
	 * Sets the service info ID of this dossier.
	 *
	 * @param serviceInfoId the service info ID of this dossier
	 */
	public void setServiceInfoId(long serviceInfoId);

	/**
	 * Returns the service domain index of this dossier.
	 *
	 * @return the service domain index of this dossier
	 */
	@AutoEscape
	public String getServiceDomainIndex();

	/**
	 * Sets the service domain index of this dossier.
	 *
	 * @param serviceDomainIndex the service domain index of this dossier
	 */
	public void setServiceDomainIndex(String serviceDomainIndex);

	/**
	 * Returns the service administration index of this dossier.
	 *
	 * @return the service administration index of this dossier
	 */
	@AutoEscape
	public String getServiceAdministrationIndex();

	/**
	 * Sets the service administration index of this dossier.
	 *
	 * @param serviceAdministrationIndex the service administration index of this dossier
	 */
	public void setServiceAdministrationIndex(String serviceAdministrationIndex);

	/**
	 * Returns the dossier template ID of this dossier.
	 *
	 * @return the dossier template ID of this dossier
	 */
	public long getDossierTemplateId();

	/**
	 * Sets the dossier template ID of this dossier.
	 *
	 * @param dossierTemplateId the dossier template ID of this dossier
	 */
	public void setDossierTemplateId(long dossierTemplateId);

	/**
	 * Returns the gov agency code of this dossier.
	 *
	 * @return the gov agency code of this dossier
	 */
	@AutoEscape
	public String getGovAgencyCode();

	/**
	 * Sets the gov agency code of this dossier.
	 *
	 * @param govAgencyCode the gov agency code of this dossier
	 */
	public void setGovAgencyCode(String govAgencyCode);

	/**
	 * Returns the gov agency name of this dossier.
	 *
	 * @return the gov agency name of this dossier
	 */
	@AutoEscape
	public String getGovAgencyName();

	/**
	 * Sets the gov agency name of this dossier.
	 *
	 * @param govAgencyName the gov agency name of this dossier
	 */
	public void setGovAgencyName(String govAgencyName);

	/**
	 * Returns the gov agency organization ID of this dossier.
	 *
	 * @return the gov agency organization ID of this dossier
	 */
	public long getGovAgencyOrganizationId();

	/**
	 * Sets the gov agency organization ID of this dossier.
	 *
	 * @param govAgencyOrganizationId the gov agency organization ID of this dossier
	 */
	public void setGovAgencyOrganizationId(long govAgencyOrganizationId);

	/**
	 * Returns the service mode of this dossier.
	 *
	 * @return the service mode of this dossier
	 */
	public int getServiceMode();

	/**
	 * Sets the service mode of this dossier.
	 *
	 * @param serviceMode the service mode of this dossier
	 */
	public void setServiceMode(int serviceMode);

	/**
	 * Returns the counter of this dossier.
	 *
	 * @return the counter of this dossier
	 */
	public int getCounter();

	/**
	 * Sets the counter of this dossier.
	 *
	 * @param counter the counter of this dossier
	 */
	public void setCounter(int counter);

	/**
	 * Returns the subject ID of this dossier.
	 *
	 * @return the subject ID of this dossier
	 */
	@AutoEscape
	public String getSubjectId();

	/**
	 * Sets the subject ID of this dossier.
	 *
	 * @param subjectId the subject ID of this dossier
	 */
	public void setSubjectId(String subjectId);

	/**
	 * Returns the subject name of this dossier.
	 *
	 * @return the subject name of this dossier
	 */
	@AutoEscape
	public String getSubjectName();

	/**
	 * Sets the subject name of this dossier.
	 *
	 * @param subjectName the subject name of this dossier
	 */
	public void setSubjectName(String subjectName);

	/**
	 * Returns the address of this dossier.
	 *
	 * @return the address of this dossier
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this dossier.
	 *
	 * @param address the address of this dossier
	 */
	public void setAddress(String address);

	/**
	 * Returns the city code of this dossier.
	 *
	 * @return the city code of this dossier
	 */
	@AutoEscape
	public String getCityCode();

	/**
	 * Sets the city code of this dossier.
	 *
	 * @param cityCode the city code of this dossier
	 */
	public void setCityCode(String cityCode);

	/**
	 * Returns the city name of this dossier.
	 *
	 * @return the city name of this dossier
	 */
	@AutoEscape
	public String getCityName();

	/**
	 * Sets the city name of this dossier.
	 *
	 * @param cityName the city name of this dossier
	 */
	public void setCityName(String cityName);

	/**
	 * Returns the district code of this dossier.
	 *
	 * @return the district code of this dossier
	 */
	@AutoEscape
	public String getDistrictCode();

	/**
	 * Sets the district code of this dossier.
	 *
	 * @param districtCode the district code of this dossier
	 */
	public void setDistrictCode(String districtCode);

	/**
	 * Returns the district name of this dossier.
	 *
	 * @return the district name of this dossier
	 */
	@AutoEscape
	public String getDistrictName();

	/**
	 * Sets the district name of this dossier.
	 *
	 * @param districtName the district name of this dossier
	 */
	public void setDistrictName(String districtName);

	/**
	 * Returns the ward code of this dossier.
	 *
	 * @return the ward code of this dossier
	 */
	@AutoEscape
	public String getWardCode();

	/**
	 * Sets the ward code of this dossier.
	 *
	 * @param wardCode the ward code of this dossier
	 */
	public void setWardCode(String wardCode);

	/**
	 * Returns the ward name of this dossier.
	 *
	 * @return the ward name of this dossier
	 */
	@AutoEscape
	public String getWardName();

	/**
	 * Sets the ward name of this dossier.
	 *
	 * @param wardName the ward name of this dossier
	 */
	public void setWardName(String wardName);

	/**
	 * Returns the contact name of this dossier.
	 *
	 * @return the contact name of this dossier
	 */
	@AutoEscape
	public String getContactName();

	/**
	 * Sets the contact name of this dossier.
	 *
	 * @param contactName the contact name of this dossier
	 */
	public void setContactName(String contactName);

	/**
	 * Returns the contact tel no of this dossier.
	 *
	 * @return the contact tel no of this dossier
	 */
	@AutoEscape
	public String getContactTelNo();

	/**
	 * Sets the contact tel no of this dossier.
	 *
	 * @param contactTelNo the contact tel no of this dossier
	 */
	public void setContactTelNo(String contactTelNo);

	/**
	 * Returns the contact email of this dossier.
	 *
	 * @return the contact email of this dossier
	 */
	@AutoEscape
	public String getContactEmail();

	/**
	 * Sets the contact email of this dossier.
	 *
	 * @param contactEmail the contact email of this dossier
	 */
	public void setContactEmail(String contactEmail);

	/**
	 * Returns the note of this dossier.
	 *
	 * @return the note of this dossier
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this dossier.
	 *
	 * @param note the note of this dossier
	 */
	public void setNote(String note);

	/**
	 * Returns the submit datetime of this dossier.
	 *
	 * @return the submit datetime of this dossier
	 */
	public Date getSubmitDatetime();

	/**
	 * Sets the submit datetime of this dossier.
	 *
	 * @param submitDatetime the submit datetime of this dossier
	 */
	public void setSubmitDatetime(Date submitDatetime);

	/**
	 * Returns the receive datetime of this dossier.
	 *
	 * @return the receive datetime of this dossier
	 */
	public Date getReceiveDatetime();

	/**
	 * Sets the receive datetime of this dossier.
	 *
	 * @param receiveDatetime the receive datetime of this dossier
	 */
	public void setReceiveDatetime(Date receiveDatetime);

	/**
	 * Returns the reception no of this dossier.
	 *
	 * @return the reception no of this dossier
	 */
	@AutoEscape
	public String getReceptionNo();

	/**
	 * Sets the reception no of this dossier.
	 *
	 * @param receptionNo the reception no of this dossier
	 */
	public void setReceptionNo(String receptionNo);

	/**
	 * Returns the estimate datetime of this dossier.
	 *
	 * @return the estimate datetime of this dossier
	 */
	public Date getEstimateDatetime();

	/**
	 * Sets the estimate datetime of this dossier.
	 *
	 * @param estimateDatetime the estimate datetime of this dossier
	 */
	public void setEstimateDatetime(Date estimateDatetime);

	/**
	 * Returns the finish datetime of this dossier.
	 *
	 * @return the finish datetime of this dossier
	 */
	public Date getFinishDatetime();

	/**
	 * Sets the finish datetime of this dossier.
	 *
	 * @param finishDatetime the finish datetime of this dossier
	 */
	public void setFinishDatetime(Date finishDatetime);

	/**
	 * Returns the dossier status of this dossier.
	 *
	 * @return the dossier status of this dossier
	 */
	@AutoEscape
	public String getDossierStatus();

	/**
	 * Sets the dossier status of this dossier.
	 *
	 * @param dossierStatus the dossier status of this dossier
	 */
	public void setDossierStatus(String dossierStatus);

	/**
	 * Returns the dossier source of this dossier.
	 *
	 * @return the dossier source of this dossier
	 */
	public int getDossierSource();

	/**
	 * Sets the dossier source of this dossier.
	 *
	 * @param dossierSource the dossier source of this dossier
	 */
	public void setDossierSource(int dossierSource);

	/**
	 * Returns the keypay redirect url of this dossier.
	 *
	 * @return the keypay redirect url of this dossier
	 */
	@AutoEscape
	public String getKeypayRedirectUrl();

	/**
	 * Sets the keypay redirect url of this dossier.
	 *
	 * @param keypayRedirectUrl the keypay redirect url of this dossier
	 */
	public void setKeypayRedirectUrl(String keypayRedirectUrl);

	/**
	 * Returns the delay status of this dossier.
	 *
	 * @return the delay status of this dossier
	 */
	public int getDelayStatus();

	/**
	 * Sets the delay status of this dossier.
	 *
	 * @param delayStatus the delay status of this dossier
	 */
	public void setDelayStatus(int delayStatus);

	/**
	 * Returns the folder ID of this dossier.
	 *
	 * @return the folder ID of this dossier
	 */
	public long getFolderId();

	/**
	 * Sets the folder ID of this dossier.
	 *
	 * @param folderId the folder ID of this dossier
	 */
	public void setFolderId(long folderId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.opencps.dossiermgt.model.Dossier dossier);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.opencps.dossiermgt.model.Dossier> toCacheModel();

	@Override
	public org.opencps.dossiermgt.model.Dossier toEscapedModel();

	@Override
	public org.opencps.dossiermgt.model.Dossier toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}