/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.opencps.dossiermgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DossierTemplate service. Represents a row in the &quot;opencps_dossiertemplate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.opencps.dossiermgt.model.impl.DossierTemplateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.opencps.dossiermgt.model.impl.DossierTemplateImpl}.
 * </p>
 *
 * @author trungnt
 * @see DossierTemplate
 * @see org.opencps.dossiermgt.model.impl.DossierTemplateImpl
 * @see org.opencps.dossiermgt.model.impl.DossierTemplateModelImpl
 * @generated
 */
public interface DossierTemplateModel extends BaseModel<DossierTemplate> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dossier template model instance should use the {@link DossierTemplate} interface instead.
	 */

	/**
	 * Returns the primary key of this dossier template.
	 *
	 * @return the primary key of this dossier template
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dossier template.
	 *
	 * @param primaryKey the primary key of this dossier template
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dossier template ID of this dossier template.
	 *
	 * @return the dossier template ID of this dossier template
	 */
	public long getDossierTemplateId();

	/**
	 * Sets the dossier template ID of this dossier template.
	 *
	 * @param dossierTemplateId the dossier template ID of this dossier template
	 */
	public void setDossierTemplateId(long dossierTemplateId);

	/**
	 * Returns the company ID of this dossier template.
	 *
	 * @return the company ID of this dossier template
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this dossier template.
	 *
	 * @param companyId the company ID of this dossier template
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this dossier template.
	 *
	 * @return the group ID of this dossier template
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this dossier template.
	 *
	 * @param groupId the group ID of this dossier template
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this dossier template.
	 *
	 * @return the user ID of this dossier template
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this dossier template.
	 *
	 * @param userId the user ID of this dossier template
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dossier template.
	 *
	 * @return the user uuid of this dossier template
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this dossier template.
	 *
	 * @param userUuid the user uuid of this dossier template
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this dossier template.
	 *
	 * @return the create date of this dossier template
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this dossier template.
	 *
	 * @param createDate the create date of this dossier template
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this dossier template.
	 *
	 * @return the modified date of this dossier template
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dossier template.
	 *
	 * @param modifiedDate the modified date of this dossier template
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the template name of this dossier template.
	 *
	 * @return the template name of this dossier template
	 */
	@AutoEscape
	public String getTemplateName();

	/**
	 * Sets the template name of this dossier template.
	 *
	 * @param templateName the template name of this dossier template
	 */
	public void setTemplateName(String templateName);

	/**
	 * Returns the description of this dossier template.
	 *
	 * @return the description of this dossier template
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this dossier template.
	 *
	 * @param description the description of this dossier template
	 */
	public void setDescription(String description);

	/**
	 * Returns the template no of this dossier template.
	 *
	 * @return the template no of this dossier template
	 */
	@AutoEscape
	public String getTemplateNo();

	/**
	 * Sets the template no of this dossier template.
	 *
	 * @param templateNo the template no of this dossier template
	 */
	public void setTemplateNo(String templateNo);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.opencps.dossiermgt.model.DossierTemplate dossierTemplate);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.opencps.dossiermgt.model.DossierTemplate> toCacheModel();

	@Override
	public org.opencps.dossiermgt.model.DossierTemplate toEscapedModel();

	@Override
	public org.opencps.dossiermgt.model.DossierTemplate toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}