/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.opencps.dossiermgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DossierLog service. Represents a row in the &quot;opencps_dossier_log&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.opencps.dossiermgt.model.impl.DossierLogModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.opencps.dossiermgt.model.impl.DossierLogImpl}.
 * </p>
 *
 * @author trungnt
 * @see DossierLog
 * @see org.opencps.dossiermgt.model.impl.DossierLogImpl
 * @see org.opencps.dossiermgt.model.impl.DossierLogModelImpl
 * @generated
 */
public interface DossierLogModel extends BaseModel<DossierLog> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dossier log model instance should use the {@link DossierLog} interface instead.
	 */

	/**
	 * Returns the primary key of this dossier log.
	 *
	 * @return the primary key of this dossier log
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dossier log.
	 *
	 * @param primaryKey the primary key of this dossier log
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dossier log ID of this dossier log.
	 *
	 * @return the dossier log ID of this dossier log
	 */
	public long getDossierLogId();

	/**
	 * Sets the dossier log ID of this dossier log.
	 *
	 * @param dossierLogId the dossier log ID of this dossier log
	 */
	public void setDossierLogId(long dossierLogId);

	/**
	 * Returns the company ID of this dossier log.
	 *
	 * @return the company ID of this dossier log
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this dossier log.
	 *
	 * @param companyId the company ID of this dossier log
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this dossier log.
	 *
	 * @return the group ID of this dossier log
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this dossier log.
	 *
	 * @param groupId the group ID of this dossier log
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this dossier log.
	 *
	 * @return the user ID of this dossier log
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this dossier log.
	 *
	 * @param userId the user ID of this dossier log
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dossier log.
	 *
	 * @return the user uuid of this dossier log
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this dossier log.
	 *
	 * @param userUuid the user uuid of this dossier log
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this dossier log.
	 *
	 * @return the create date of this dossier log
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this dossier log.
	 *
	 * @param createDate the create date of this dossier log
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this dossier log.
	 *
	 * @return the modified date of this dossier log
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dossier log.
	 *
	 * @param modifiedDate the modified date of this dossier log
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the dossier ID of this dossier log.
	 *
	 * @return the dossier ID of this dossier log
	 */
	public long getDossierId();

	/**
	 * Sets the dossier ID of this dossier log.
	 *
	 * @param dossierId the dossier ID of this dossier log
	 */
	public void setDossierId(long dossierId);

	/**
	 * Returns the file group ID of this dossier log.
	 *
	 * @return the file group ID of this dossier log
	 */
	public long getFileGroupId();

	/**
	 * Sets the file group ID of this dossier log.
	 *
	 * @param fileGroupId the file group ID of this dossier log
	 */
	public void setFileGroupId(long fileGroupId);

	/**
	 * Returns the request command of this dossier log.
	 *
	 * @return the request command of this dossier log
	 */
	@AutoEscape
	public String getRequestCommand();

	/**
	 * Sets the request command of this dossier log.
	 *
	 * @param requestCommand the request command of this dossier log
	 */
	public void setRequestCommand(String requestCommand);

	/**
	 * Returns the dossier status of this dossier log.
	 *
	 * @return the dossier status of this dossier log
	 */
	@AutoEscape
	public String getDossierStatus();

	/**
	 * Sets the dossier status of this dossier log.
	 *
	 * @param dossierStatus the dossier status of this dossier log
	 */
	public void setDossierStatus(String dossierStatus);

	/**
	 * Returns the action info of this dossier log.
	 *
	 * @return the action info of this dossier log
	 */
	@AutoEscape
	public String getActionInfo();

	/**
	 * Sets the action info of this dossier log.
	 *
	 * @param actionInfo the action info of this dossier log
	 */
	public void setActionInfo(String actionInfo);

	/**
	 * Returns the message info of this dossier log.
	 *
	 * @return the message info of this dossier log
	 */
	@AutoEscape
	public String getMessageInfo();

	/**
	 * Sets the message info of this dossier log.
	 *
	 * @param messageInfo the message info of this dossier log
	 */
	public void setMessageInfo(String messageInfo);

	/**
	 * Returns the update datetime of this dossier log.
	 *
	 * @return the update datetime of this dossier log
	 */
	public Date getUpdateDatetime();

	/**
	 * Sets the update datetime of this dossier log.
	 *
	 * @param updateDatetime the update datetime of this dossier log
	 */
	public void setUpdateDatetime(Date updateDatetime);

	/**
	 * Returns the level of this dossier log.
	 *
	 * @return the level of this dossier log
	 */
	public int getLevel();

	/**
	 * Sets the level of this dossier log.
	 *
	 * @param level the level of this dossier log
	 */
	public void setLevel(int level);

	/**
	 * Returns the actor of this dossier log.
	 *
	 * @return the actor of this dossier log
	 */
	public int getActor();

	/**
	 * Sets the actor of this dossier log.
	 *
	 * @param actor the actor of this dossier log
	 */
	public void setActor(int actor);

	/**
	 * Returns the actor ID of this dossier log.
	 *
	 * @return the actor ID of this dossier log
	 */
	public long getActorId();

	/**
	 * Sets the actor ID of this dossier log.
	 *
	 * @param actorId the actor ID of this dossier log
	 */
	public void setActorId(long actorId);

	/**
	 * Returns the actor name of this dossier log.
	 *
	 * @return the actor name of this dossier log
	 */
	@AutoEscape
	public String getActorName();

	/**
	 * Sets the actor name of this dossier log.
	 *
	 * @param actorName the actor name of this dossier log
	 */
	public void setActorName(String actorName);

	/**
	 * Returns the sync status of this dossier log.
	 *
	 * @return the sync status of this dossier log
	 */
	public int getSyncStatus();

	/**
	 * Sets the sync status of this dossier log.
	 *
	 * @param syncStatus the sync status of this dossier log
	 */
	public void setSyncStatus(int syncStatus);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.opencps.dossiermgt.model.DossierLog dossierLog);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.opencps.dossiermgt.model.DossierLog> toCacheModel();

	@Override
	public org.opencps.dossiermgt.model.DossierLog toEscapedModel();

	@Override
	public org.opencps.dossiermgt.model.DossierLog toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}