/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.opencps.dossiermgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FileGroup service. Represents a row in the &quot;opencps_file_group&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.opencps.dossiermgt.model.impl.FileGroupModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.opencps.dossiermgt.model.impl.FileGroupImpl}.
 * </p>
 *
 * @author trungnt
 * @see FileGroup
 * @see org.opencps.dossiermgt.model.impl.FileGroupImpl
 * @see org.opencps.dossiermgt.model.impl.FileGroupModelImpl
 * @generated
 */
public interface FileGroupModel extends BaseModel<FileGroup> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a file group model instance should use the {@link FileGroup} interface instead.
	 */

	/**
	 * Returns the primary key of this file group.
	 *
	 * @return the primary key of this file group
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this file group.
	 *
	 * @param primaryKey the primary key of this file group
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the file group ID of this file group.
	 *
	 * @return the file group ID of this file group
	 */
	public long getFileGroupId();

	/**
	 * Sets the file group ID of this file group.
	 *
	 * @param fileGroupId the file group ID of this file group
	 */
	public void setFileGroupId(long fileGroupId);

	/**
	 * Returns the company ID of this file group.
	 *
	 * @return the company ID of this file group
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this file group.
	 *
	 * @param companyId the company ID of this file group
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this file group.
	 *
	 * @return the group ID of this file group
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this file group.
	 *
	 * @param groupId the group ID of this file group
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this file group.
	 *
	 * @return the user ID of this file group
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this file group.
	 *
	 * @param userId the user ID of this file group
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this file group.
	 *
	 * @return the user uuid of this file group
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this file group.
	 *
	 * @param userUuid the user uuid of this file group
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this file group.
	 *
	 * @return the create date of this file group
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this file group.
	 *
	 * @param createDate the create date of this file group
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this file group.
	 *
	 * @return the modified date of this file group
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this file group.
	 *
	 * @param modifiedDate the modified date of this file group
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the o ID of this file group.
	 *
	 * @return the o ID of this file group
	 */
	@AutoEscape
	public String getOId();

	/**
	 * Sets the o ID of this file group.
	 *
	 * @param oId the o ID of this file group
	 */
	public void setOId(String oId);

	/**
	 * Returns the dossier ID of this file group.
	 *
	 * @return the dossier ID of this file group
	 */
	public long getDossierId();

	/**
	 * Sets the dossier ID of this file group.
	 *
	 * @param dossierId the dossier ID of this file group
	 */
	public void setDossierId(long dossierId);

	/**
	 * Returns the dossier part ID of this file group.
	 *
	 * @return the dossier part ID of this file group
	 */
	public long getDossierPartId();

	/**
	 * Sets the dossier part ID of this file group.
	 *
	 * @param dossierPartId the dossier part ID of this file group
	 */
	public void setDossierPartId(long dossierPartId);

	/**
	 * Returns the display name of this file group.
	 *
	 * @return the display name of this file group
	 */
	@AutoEscape
	public String getDisplayName();

	/**
	 * Sets the display name of this file group.
	 *
	 * @param displayName the display name of this file group
	 */
	public void setDisplayName(String displayName);

	/**
	 * Returns the removed of this file group.
	 *
	 * @return the removed of this file group
	 */
	public int getRemoved();

	/**
	 * Sets the removed of this file group.
	 *
	 * @param removed the removed of this file group
	 */
	public void setRemoved(int removed);

	/**
	 * Returns the sync status of this file group.
	 *
	 * @return the sync status of this file group
	 */
	public int getSyncStatus();

	/**
	 * Sets the sync status of this file group.
	 *
	 * @param syncStatus the sync status of this file group
	 */
	public void setSyncStatus(int syncStatus);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.opencps.dossiermgt.model.FileGroup fileGroup);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.opencps.dossiermgt.model.FileGroup> toCacheModel();

	@Override
	public org.opencps.dossiermgt.model.FileGroup toEscapedModel();

	@Override
	public org.opencps.dossiermgt.model.FileGroup toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}