/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.opencps.dossiermgt.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.opencps.dossiermgt.model.DossierFile;
import org.opencps.dossiermgt.model.DossierFileModel;
import org.opencps.dossiermgt.model.DossierFileSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the DossierFile service. Represents a row in the &quot;opencps_dossier_file&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.opencps.dossiermgt.model.DossierFileModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DossierFileImpl}.
 * </p>
 *
 * @author trungnt
 * @see DossierFileImpl
 * @see org.opencps.dossiermgt.model.DossierFile
 * @see org.opencps.dossiermgt.model.DossierFileModel
 * @generated
 */
@JSON(strict = true)
public class DossierFileModelImpl extends BaseModelImpl<DossierFile>
	implements DossierFileModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dossier file model instance should use the {@link org.opencps.dossiermgt.model.DossierFile} interface instead.
	 */
	public static final String TABLE_NAME = "opencps_dossier_file";
	public static final Object[][] TABLE_COLUMNS = {
			{ "dossierFileId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "dossierId", Types.BIGINT },
			{ "oid", Types.VARCHAR },
			{ "dossierPartId", Types.BIGINT },
			{ "templateFileNo", Types.VARCHAR },
			{ "groupFileId", Types.BIGINT },
			{ "ownerUserId", Types.BIGINT },
			{ "ownerOrganizationId", Types.BIGINT },
			{ "govAgencyOrganizationId", Types.INTEGER },
			{ "displayName", Types.VARCHAR },
			{ "formData", Types.VARCHAR },
			{ "fileEntryId", Types.BIGINT },
			{ "dossierFileMark", Types.INTEGER },
			{ "dossierFileType", Types.INTEGER },
			{ "dossierFileNo", Types.VARCHAR },
			{ "dossierFileDate", Types.TIMESTAMP },
			{ "removed", Types.INTEGER },
			{ "original", Types.INTEGER },
			{ "syncStatus", Types.INTEGER },
			{ "version", Types.INTEGER },
			{ "signed", Types.BOOLEAN }
		};
	public static final String TABLE_SQL_CREATE = "create table opencps_dossier_file (dossierFileId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,dossierId LONG,oid VARCHAR(75) null,dossierPartId LONG,templateFileNo VARCHAR(75) null,groupFileId LONG,ownerUserId LONG,ownerOrganizationId LONG,govAgencyOrganizationId INTEGER,displayName VARCHAR(255) null,formData STRING null,fileEntryId LONG,dossierFileMark INTEGER,dossierFileType INTEGER,dossierFileNo VARCHAR(255) null,dossierFileDate DATE null,removed INTEGER,original INTEGER,syncStatus INTEGER,version INTEGER,signed BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table opencps_dossier_file";
	public static final String ORDER_BY_JPQL = " ORDER BY dossierFile.dossierFileId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY opencps_dossier_file.dossierFileId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.opencps.dossiermgt.model.DossierFile"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.opencps.dossiermgt.model.DossierFile"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.opencps.dossiermgt.model.DossierFile"),
			true);
	public static long DOSSIERID_COLUMN_BITMASK = 1L;
	public static long DOSSIERPARTID_COLUMN_BITMASK = 2L;
	public static long GROUPFILEID_COLUMN_BITMASK = 4L;
	public static long OID_COLUMN_BITMASK = 8L;
	public static long REMOVED_COLUMN_BITMASK = 16L;
	public static long SYNCSTATUS_COLUMN_BITMASK = 32L;
	public static long TEMPLATEFILENO_COLUMN_BITMASK = 64L;
	public static long DOSSIERFILEID_COLUMN_BITMASK = 128L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static DossierFile toModel(DossierFileSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		DossierFile model = new DossierFileImpl();

		model.setDossierFileId(soapModel.getDossierFileId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setDossierId(soapModel.getDossierId());
		model.setOid(soapModel.getOid());
		model.setDossierPartId(soapModel.getDossierPartId());
		model.setTemplateFileNo(soapModel.getTemplateFileNo());
		model.setGroupFileId(soapModel.getGroupFileId());
		model.setOwnerUserId(soapModel.getOwnerUserId());
		model.setOwnerOrganizationId(soapModel.getOwnerOrganizationId());
		model.setGovAgencyOrganizationId(soapModel.getGovAgencyOrganizationId());
		model.setDisplayName(soapModel.getDisplayName());
		model.setFormData(soapModel.getFormData());
		model.setFileEntryId(soapModel.getFileEntryId());
		model.setDossierFileMark(soapModel.getDossierFileMark());
		model.setDossierFileType(soapModel.getDossierFileType());
		model.setDossierFileNo(soapModel.getDossierFileNo());
		model.setDossierFileDate(soapModel.getDossierFileDate());
		model.setRemoved(soapModel.getRemoved());
		model.setOriginal(soapModel.getOriginal());
		model.setSyncStatus(soapModel.getSyncStatus());
		model.setVersion(soapModel.getVersion());
		model.setSigned(soapModel.getSigned());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<DossierFile> toModels(DossierFileSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<DossierFile> models = new ArrayList<DossierFile>(soapModels.length);

		for (DossierFileSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.opencps.dossiermgt.model.DossierFile"));

	public DossierFileModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _dossierFileId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDossierFileId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _dossierFileId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DossierFile.class;
	}

	@Override
	public String getModelClassName() {
		return DossierFile.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("dossierFileId", getDossierFileId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("dossierId", getDossierId());
		attributes.put("oid", getOid());
		attributes.put("dossierPartId", getDossierPartId());
		attributes.put("templateFileNo", getTemplateFileNo());
		attributes.put("groupFileId", getGroupFileId());
		attributes.put("ownerUserId", getOwnerUserId());
		attributes.put("ownerOrganizationId", getOwnerOrganizationId());
		attributes.put("govAgencyOrganizationId", getGovAgencyOrganizationId());
		attributes.put("displayName", getDisplayName());
		attributes.put("formData", getFormData());
		attributes.put("fileEntryId", getFileEntryId());
		attributes.put("dossierFileMark", getDossierFileMark());
		attributes.put("dossierFileType", getDossierFileType());
		attributes.put("dossierFileNo", getDossierFileNo());
		attributes.put("dossierFileDate", getDossierFileDate());
		attributes.put("removed", getRemoved());
		attributes.put("original", getOriginal());
		attributes.put("syncStatus", getSyncStatus());
		attributes.put("version", getVersion());
		attributes.put("signed", getSigned());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long dossierFileId = (Long)attributes.get("dossierFileId");

		if (dossierFileId != null) {
			setDossierFileId(dossierFileId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long dossierId = (Long)attributes.get("dossierId");

		if (dossierId != null) {
			setDossierId(dossierId);
		}

		String oid = (String)attributes.get("oid");

		if (oid != null) {
			setOid(oid);
		}

		Long dossierPartId = (Long)attributes.get("dossierPartId");

		if (dossierPartId != null) {
			setDossierPartId(dossierPartId);
		}

		String templateFileNo = (String)attributes.get("templateFileNo");

		if (templateFileNo != null) {
			setTemplateFileNo(templateFileNo);
		}

		Long groupFileId = (Long)attributes.get("groupFileId");

		if (groupFileId != null) {
			setGroupFileId(groupFileId);
		}

		Long ownerUserId = (Long)attributes.get("ownerUserId");

		if (ownerUserId != null) {
			setOwnerUserId(ownerUserId);
		}

		Long ownerOrganizationId = (Long)attributes.get("ownerOrganizationId");

		if (ownerOrganizationId != null) {
			setOwnerOrganizationId(ownerOrganizationId);
		}

		Integer govAgencyOrganizationId = (Integer)attributes.get(
				"govAgencyOrganizationId");

		if (govAgencyOrganizationId != null) {
			setGovAgencyOrganizationId(govAgencyOrganizationId);
		}

		String displayName = (String)attributes.get("displayName");

		if (displayName != null) {
			setDisplayName(displayName);
		}

		String formData = (String)attributes.get("formData");

		if (formData != null) {
			setFormData(formData);
		}

		Long fileEntryId = (Long)attributes.get("fileEntryId");

		if (fileEntryId != null) {
			setFileEntryId(fileEntryId);
		}

		Integer dossierFileMark = (Integer)attributes.get("dossierFileMark");

		if (dossierFileMark != null) {
			setDossierFileMark(dossierFileMark);
		}

		Integer dossierFileType = (Integer)attributes.get("dossierFileType");

		if (dossierFileType != null) {
			setDossierFileType(dossierFileType);
		}

		String dossierFileNo = (String)attributes.get("dossierFileNo");

		if (dossierFileNo != null) {
			setDossierFileNo(dossierFileNo);
		}

		Date dossierFileDate = (Date)attributes.get("dossierFileDate");

		if (dossierFileDate != null) {
			setDossierFileDate(dossierFileDate);
		}

		Integer removed = (Integer)attributes.get("removed");

		if (removed != null) {
			setRemoved(removed);
		}

		Integer original = (Integer)attributes.get("original");

		if (original != null) {
			setOriginal(original);
		}

		Integer syncStatus = (Integer)attributes.get("syncStatus");

		if (syncStatus != null) {
			setSyncStatus(syncStatus);
		}

		Integer version = (Integer)attributes.get("version");

		if (version != null) {
			setVersion(version);
		}

		Boolean signed = (Boolean)attributes.get("signed");

		if (signed != null) {
			setSigned(signed);
		}
	}

	@JSON
	@Override
	public long getDossierFileId() {
		return _dossierFileId;
	}

	@Override
	public void setDossierFileId(long dossierFileId) {
		_dossierFileId = dossierFileId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getDossierId() {
		return _dossierId;
	}

	@Override
	public void setDossierId(long dossierId) {
		_columnBitmask |= DOSSIERID_COLUMN_BITMASK;

		if (!_setOriginalDossierId) {
			_setOriginalDossierId = true;

			_originalDossierId = _dossierId;
		}

		_dossierId = dossierId;
	}

	public long getOriginalDossierId() {
		return _originalDossierId;
	}

	@JSON
	@Override
	public String getOid() {
		if (_oid == null) {
			return StringPool.BLANK;
		}
		else {
			return _oid;
		}
	}

	@Override
	public void setOid(String oid) {
		_columnBitmask |= OID_COLUMN_BITMASK;

		if (_originalOid == null) {
			_originalOid = _oid;
		}

		_oid = oid;
	}

	public String getOriginalOid() {
		return GetterUtil.getString(_originalOid);
	}

	@JSON
	@Override
	public long getDossierPartId() {
		return _dossierPartId;
	}

	@Override
	public void setDossierPartId(long dossierPartId) {
		_columnBitmask |= DOSSIERPARTID_COLUMN_BITMASK;

		if (!_setOriginalDossierPartId) {
			_setOriginalDossierPartId = true;

			_originalDossierPartId = _dossierPartId;
		}

		_dossierPartId = dossierPartId;
	}

	public long getOriginalDossierPartId() {
		return _originalDossierPartId;
	}

	@JSON
	@Override
	public String getTemplateFileNo() {
		if (_templateFileNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _templateFileNo;
		}
	}

	@Override
	public void setTemplateFileNo(String templateFileNo) {
		_columnBitmask |= TEMPLATEFILENO_COLUMN_BITMASK;

		if (_originalTemplateFileNo == null) {
			_originalTemplateFileNo = _templateFileNo;
		}

		_templateFileNo = templateFileNo;
	}

	public String getOriginalTemplateFileNo() {
		return GetterUtil.getString(_originalTemplateFileNo);
	}

	@JSON
	@Override
	public long getGroupFileId() {
		return _groupFileId;
	}

	@Override
	public void setGroupFileId(long groupFileId) {
		_columnBitmask |= GROUPFILEID_COLUMN_BITMASK;

		if (!_setOriginalGroupFileId) {
			_setOriginalGroupFileId = true;

			_originalGroupFileId = _groupFileId;
		}

		_groupFileId = groupFileId;
	}

	public long getOriginalGroupFileId() {
		return _originalGroupFileId;
	}

	@JSON
	@Override
	public long getOwnerUserId() {
		return _ownerUserId;
	}

	@Override
	public void setOwnerUserId(long ownerUserId) {
		_ownerUserId = ownerUserId;
	}

	@Override
	public String getOwnerUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getOwnerUserId(), "uuid", _ownerUserUuid);
	}

	@Override
	public void setOwnerUserUuid(String ownerUserUuid) {
		_ownerUserUuid = ownerUserUuid;
	}

	@JSON
	@Override
	public long getOwnerOrganizationId() {
		return _ownerOrganizationId;
	}

	@Override
	public void setOwnerOrganizationId(long ownerOrganizationId) {
		_ownerOrganizationId = ownerOrganizationId;
	}

	@JSON
	@Override
	public int getGovAgencyOrganizationId() {
		return _govAgencyOrganizationId;
	}

	@Override
	public void setGovAgencyOrganizationId(int govAgencyOrganizationId) {
		_govAgencyOrganizationId = govAgencyOrganizationId;
	}

	@JSON
	@Override
	public String getDisplayName() {
		if (_displayName == null) {
			return StringPool.BLANK;
		}
		else {
			return _displayName;
		}
	}

	@Override
	public void setDisplayName(String displayName) {
		_displayName = displayName;
	}

	@JSON
	@Override
	public String getFormData() {
		if (_formData == null) {
			return StringPool.BLANK;
		}
		else {
			return _formData;
		}
	}

	@Override
	public void setFormData(String formData) {
		_formData = formData;
	}

	@JSON
	@Override
	public long getFileEntryId() {
		return _fileEntryId;
	}

	@Override
	public void setFileEntryId(long fileEntryId) {
		_fileEntryId = fileEntryId;
	}

	@JSON
	@Override
	public int getDossierFileMark() {
		return _dossierFileMark;
	}

	@Override
	public void setDossierFileMark(int dossierFileMark) {
		_dossierFileMark = dossierFileMark;
	}

	@JSON
	@Override
	public int getDossierFileType() {
		return _dossierFileType;
	}

	@Override
	public void setDossierFileType(int dossierFileType) {
		_dossierFileType = dossierFileType;
	}

	@JSON
	@Override
	public String getDossierFileNo() {
		if (_dossierFileNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _dossierFileNo;
		}
	}

	@Override
	public void setDossierFileNo(String dossierFileNo) {
		_dossierFileNo = dossierFileNo;
	}

	@JSON
	@Override
	public Date getDossierFileDate() {
		return _dossierFileDate;
	}

	@Override
	public void setDossierFileDate(Date dossierFileDate) {
		_dossierFileDate = dossierFileDate;
	}

	@JSON
	@Override
	public int getRemoved() {
		return _removed;
	}

	@Override
	public void setRemoved(int removed) {
		_columnBitmask |= REMOVED_COLUMN_BITMASK;

		if (!_setOriginalRemoved) {
			_setOriginalRemoved = true;

			_originalRemoved = _removed;
		}

		_removed = removed;
	}

	public int getOriginalRemoved() {
		return _originalRemoved;
	}

	@JSON
	@Override
	public int getOriginal() {
		return _original;
	}

	@Override
	public void setOriginal(int original) {
		_original = original;
	}

	@JSON
	@Override
	public int getSyncStatus() {
		return _syncStatus;
	}

	@Override
	public void setSyncStatus(int syncStatus) {
		_columnBitmask |= SYNCSTATUS_COLUMN_BITMASK;

		if (!_setOriginalSyncStatus) {
			_setOriginalSyncStatus = true;

			_originalSyncStatus = _syncStatus;
		}

		_syncStatus = syncStatus;
	}

	public int getOriginalSyncStatus() {
		return _originalSyncStatus;
	}

	@JSON
	@Override
	public int getVersion() {
		return _version;
	}

	@Override
	public void setVersion(int version) {
		_version = version;
	}

	@JSON
	@Override
	public boolean getSigned() {
		return _signed;
	}

	@Override
	public boolean isSigned() {
		return _signed;
	}

	@Override
	public void setSigned(boolean signed) {
		_signed = signed;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			DossierFile.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DossierFile toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (DossierFile)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DossierFileImpl dossierFileImpl = new DossierFileImpl();

		dossierFileImpl.setDossierFileId(getDossierFileId());
		dossierFileImpl.setCompanyId(getCompanyId());
		dossierFileImpl.setGroupId(getGroupId());
		dossierFileImpl.setUserId(getUserId());
		dossierFileImpl.setCreateDate(getCreateDate());
		dossierFileImpl.setModifiedDate(getModifiedDate());
		dossierFileImpl.setDossierId(getDossierId());
		dossierFileImpl.setOid(getOid());
		dossierFileImpl.setDossierPartId(getDossierPartId());
		dossierFileImpl.setTemplateFileNo(getTemplateFileNo());
		dossierFileImpl.setGroupFileId(getGroupFileId());
		dossierFileImpl.setOwnerUserId(getOwnerUserId());
		dossierFileImpl.setOwnerOrganizationId(getOwnerOrganizationId());
		dossierFileImpl.setGovAgencyOrganizationId(getGovAgencyOrganizationId());
		dossierFileImpl.setDisplayName(getDisplayName());
		dossierFileImpl.setFormData(getFormData());
		dossierFileImpl.setFileEntryId(getFileEntryId());
		dossierFileImpl.setDossierFileMark(getDossierFileMark());
		dossierFileImpl.setDossierFileType(getDossierFileType());
		dossierFileImpl.setDossierFileNo(getDossierFileNo());
		dossierFileImpl.setDossierFileDate(getDossierFileDate());
		dossierFileImpl.setRemoved(getRemoved());
		dossierFileImpl.setOriginal(getOriginal());
		dossierFileImpl.setSyncStatus(getSyncStatus());
		dossierFileImpl.setVersion(getVersion());
		dossierFileImpl.setSigned(getSigned());

		dossierFileImpl.resetOriginalValues();

		return dossierFileImpl;
	}

	@Override
	public int compareTo(DossierFile dossierFile) {
		long primaryKey = dossierFile.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DossierFile)) {
			return false;
		}

		DossierFile dossierFile = (DossierFile)obj;

		long primaryKey = dossierFile.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		DossierFileModelImpl dossierFileModelImpl = this;

		dossierFileModelImpl._originalDossierId = dossierFileModelImpl._dossierId;

		dossierFileModelImpl._setOriginalDossierId = false;

		dossierFileModelImpl._originalOid = dossierFileModelImpl._oid;

		dossierFileModelImpl._originalDossierPartId = dossierFileModelImpl._dossierPartId;

		dossierFileModelImpl._setOriginalDossierPartId = false;

		dossierFileModelImpl._originalTemplateFileNo = dossierFileModelImpl._templateFileNo;

		dossierFileModelImpl._originalGroupFileId = dossierFileModelImpl._groupFileId;

		dossierFileModelImpl._setOriginalGroupFileId = false;

		dossierFileModelImpl._originalRemoved = dossierFileModelImpl._removed;

		dossierFileModelImpl._setOriginalRemoved = false;

		dossierFileModelImpl._originalSyncStatus = dossierFileModelImpl._syncStatus;

		dossierFileModelImpl._setOriginalSyncStatus = false;

		dossierFileModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DossierFile> toCacheModel() {
		DossierFileCacheModel dossierFileCacheModel = new DossierFileCacheModel();

		dossierFileCacheModel.dossierFileId = getDossierFileId();

		dossierFileCacheModel.companyId = getCompanyId();

		dossierFileCacheModel.groupId = getGroupId();

		dossierFileCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			dossierFileCacheModel.createDate = createDate.getTime();
		}
		else {
			dossierFileCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			dossierFileCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			dossierFileCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		dossierFileCacheModel.dossierId = getDossierId();

		dossierFileCacheModel.oid = getOid();

		String oid = dossierFileCacheModel.oid;

		if ((oid != null) && (oid.length() == 0)) {
			dossierFileCacheModel.oid = null;
		}

		dossierFileCacheModel.dossierPartId = getDossierPartId();

		dossierFileCacheModel.templateFileNo = getTemplateFileNo();

		String templateFileNo = dossierFileCacheModel.templateFileNo;

		if ((templateFileNo != null) && (templateFileNo.length() == 0)) {
			dossierFileCacheModel.templateFileNo = null;
		}

		dossierFileCacheModel.groupFileId = getGroupFileId();

		dossierFileCacheModel.ownerUserId = getOwnerUserId();

		dossierFileCacheModel.ownerOrganizationId = getOwnerOrganizationId();

		dossierFileCacheModel.govAgencyOrganizationId = getGovAgencyOrganizationId();

		dossierFileCacheModel.displayName = getDisplayName();

		String displayName = dossierFileCacheModel.displayName;

		if ((displayName != null) && (displayName.length() == 0)) {
			dossierFileCacheModel.displayName = null;
		}

		dossierFileCacheModel.formData = getFormData();

		String formData = dossierFileCacheModel.formData;

		if ((formData != null) && (formData.length() == 0)) {
			dossierFileCacheModel.formData = null;
		}

		dossierFileCacheModel.fileEntryId = getFileEntryId();

		dossierFileCacheModel.dossierFileMark = getDossierFileMark();

		dossierFileCacheModel.dossierFileType = getDossierFileType();

		dossierFileCacheModel.dossierFileNo = getDossierFileNo();

		String dossierFileNo = dossierFileCacheModel.dossierFileNo;

		if ((dossierFileNo != null) && (dossierFileNo.length() == 0)) {
			dossierFileCacheModel.dossierFileNo = null;
		}

		Date dossierFileDate = getDossierFileDate();

		if (dossierFileDate != null) {
			dossierFileCacheModel.dossierFileDate = dossierFileDate.getTime();
		}
		else {
			dossierFileCacheModel.dossierFileDate = Long.MIN_VALUE;
		}

		dossierFileCacheModel.removed = getRemoved();

		dossierFileCacheModel.original = getOriginal();

		dossierFileCacheModel.syncStatus = getSyncStatus();

		dossierFileCacheModel.version = getVersion();

		dossierFileCacheModel.signed = getSigned();

		return dossierFileCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(53);

		sb.append("{dossierFileId=");
		sb.append(getDossierFileId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", dossierId=");
		sb.append(getDossierId());
		sb.append(", oid=");
		sb.append(getOid());
		sb.append(", dossierPartId=");
		sb.append(getDossierPartId());
		sb.append(", templateFileNo=");
		sb.append(getTemplateFileNo());
		sb.append(", groupFileId=");
		sb.append(getGroupFileId());
		sb.append(", ownerUserId=");
		sb.append(getOwnerUserId());
		sb.append(", ownerOrganizationId=");
		sb.append(getOwnerOrganizationId());
		sb.append(", govAgencyOrganizationId=");
		sb.append(getGovAgencyOrganizationId());
		sb.append(", displayName=");
		sb.append(getDisplayName());
		sb.append(", formData=");
		sb.append(getFormData());
		sb.append(", fileEntryId=");
		sb.append(getFileEntryId());
		sb.append(", dossierFileMark=");
		sb.append(getDossierFileMark());
		sb.append(", dossierFileType=");
		sb.append(getDossierFileType());
		sb.append(", dossierFileNo=");
		sb.append(getDossierFileNo());
		sb.append(", dossierFileDate=");
		sb.append(getDossierFileDate());
		sb.append(", removed=");
		sb.append(getRemoved());
		sb.append(", original=");
		sb.append(getOriginal());
		sb.append(", syncStatus=");
		sb.append(getSyncStatus());
		sb.append(", version=");
		sb.append(getVersion());
		sb.append(", signed=");
		sb.append(getSigned());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(82);

		sb.append("<model><model-name>");
		sb.append("org.opencps.dossiermgt.model.DossierFile");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>dossierFileId</column-name><column-value><![CDATA[");
		sb.append(getDossierFileId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierId</column-name><column-value><![CDATA[");
		sb.append(getDossierId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>oid</column-name><column-value><![CDATA[");
		sb.append(getOid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierPartId</column-name><column-value><![CDATA[");
		sb.append(getDossierPartId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>templateFileNo</column-name><column-value><![CDATA[");
		sb.append(getTemplateFileNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupFileId</column-name><column-value><![CDATA[");
		sb.append(getGroupFileId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ownerUserId</column-name><column-value><![CDATA[");
		sb.append(getOwnerUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ownerOrganizationId</column-name><column-value><![CDATA[");
		sb.append(getOwnerOrganizationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>govAgencyOrganizationId</column-name><column-value><![CDATA[");
		sb.append(getGovAgencyOrganizationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>displayName</column-name><column-value><![CDATA[");
		sb.append(getDisplayName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>formData</column-name><column-value><![CDATA[");
		sb.append(getFormData());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileEntryId</column-name><column-value><![CDATA[");
		sb.append(getFileEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierFileMark</column-name><column-value><![CDATA[");
		sb.append(getDossierFileMark());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierFileType</column-name><column-value><![CDATA[");
		sb.append(getDossierFileType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierFileNo</column-name><column-value><![CDATA[");
		sb.append(getDossierFileNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierFileDate</column-name><column-value><![CDATA[");
		sb.append(getDossierFileDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>removed</column-name><column-value><![CDATA[");
		sb.append(getRemoved());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>original</column-name><column-value><![CDATA[");
		sb.append(getOriginal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>syncStatus</column-name><column-value><![CDATA[");
		sb.append(getSyncStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>version</column-name><column-value><![CDATA[");
		sb.append(getVersion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>signed</column-name><column-value><![CDATA[");
		sb.append(getSigned());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DossierFile.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			DossierFile.class
		};
	private long _dossierFileId;
	private long _companyId;
	private long _groupId;
	private long _userId;
	private String _userUuid;
	private Date _createDate;
	private Date _modifiedDate;
	private long _dossierId;
	private long _originalDossierId;
	private boolean _setOriginalDossierId;
	private String _oid;
	private String _originalOid;
	private long _dossierPartId;
	private long _originalDossierPartId;
	private boolean _setOriginalDossierPartId;
	private String _templateFileNo;
	private String _originalTemplateFileNo;
	private long _groupFileId;
	private long _originalGroupFileId;
	private boolean _setOriginalGroupFileId;
	private long _ownerUserId;
	private String _ownerUserUuid;
	private long _ownerOrganizationId;
	private int _govAgencyOrganizationId;
	private String _displayName;
	private String _formData;
	private long _fileEntryId;
	private int _dossierFileMark;
	private int _dossierFileType;
	private String _dossierFileNo;
	private Date _dossierFileDate;
	private int _removed;
	private int _originalRemoved;
	private boolean _setOriginalRemoved;
	private int _original;
	private int _syncStatus;
	private int _originalSyncStatus;
	private boolean _setOriginalSyncStatus;
	private int _version;
	private boolean _signed;
	private long _columnBitmask;
	private DossierFile _escapedModel;
}