/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.opencps.api.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ApiService service. Represents a row in the &quot;opencps_api_log&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.opencps.api.model.impl.ApiServiceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.opencps.api.model.impl.ApiServiceImpl}.
 * </p>
 *
 * @author trungdk
 * @see ApiService
 * @see org.opencps.api.model.impl.ApiServiceImpl
 * @see org.opencps.api.model.impl.ApiServiceModelImpl
 * @generated
 */
public interface ApiServiceModel extends BaseModel<ApiService> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a api service model instance should use the {@link ApiService} interface instead.
	 */

	/**
	 * Returns the primary key of this api service.
	 *
	 * @return the primary key of this api service
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this api service.
	 *
	 * @param primaryKey the primary key of this api service
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the api log ID of this api service.
	 *
	 * @return the api log ID of this api service
	 */
	public long getApiLogId();

	/**
	 * Sets the api log ID of this api service.
	 *
	 * @param apiLogId the api log ID of this api service
	 */
	public void setApiLogId(long apiLogId);

	/**
	 * Returns the company ID of this api service.
	 *
	 * @return the company ID of this api service
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this api service.
	 *
	 * @param companyId the company ID of this api service
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this api service.
	 *
	 * @return the group ID of this api service
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this api service.
	 *
	 * @param groupId the group ID of this api service
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this api service.
	 *
	 * @return the user ID of this api service
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this api service.
	 *
	 * @param userId the user ID of this api service
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this api service.
	 *
	 * @return the user uuid of this api service
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this api service.
	 *
	 * @param userUuid the user uuid of this api service
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this api service.
	 *
	 * @return the create date of this api service
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this api service.
	 *
	 * @param createDate the create date of this api service
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this api service.
	 *
	 * @return the modified date of this api service
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this api service.
	 *
	 * @param modifiedDate the modified date of this api service
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the oid of this api service.
	 *
	 * @return the oid of this api service
	 */
	@AutoEscape
	public String getOid();

	/**
	 * Sets the oid of this api service.
	 *
	 * @param oid the oid of this api service
	 */
	public void setOid(String oid);

	/**
	 * Returns the api code of this api service.
	 *
	 * @return the api code of this api service
	 */
	@AutoEscape
	public String getApiCode();

	/**
	 * Sets the api code of this api service.
	 *
	 * @param apiCode the api code of this api service
	 */
	public void setApiCode(String apiCode);

	/**
	 * Returns the ip address of this api service.
	 *
	 * @return the ip address of this api service
	 */
	@AutoEscape
	public String getIpAddress();

	/**
	 * Sets the ip address of this api service.
	 *
	 * @param ipAddress the ip address of this api service
	 */
	public void setIpAddress(String ipAddress);

	/**
	 * Returns the http agent of this api service.
	 *
	 * @return the http agent of this api service
	 */
	@AutoEscape
	public String getHttpAgent();

	/**
	 * Sets the http agent of this api service.
	 *
	 * @param httpAgent the http agent of this api service
	 */
	public void setHttpAgent(String httpAgent);

	/**
	 * Returns the params of this api service.
	 *
	 * @return the params of this api service
	 */
	@AutoEscape
	public String getParams();

	/**
	 * Sets the params of this api service.
	 *
	 * @param params the params of this api service
	 */
	public void setParams(String params);

	/**
	 * Returns the status of this api service.
	 *
	 * @return the status of this api service
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this api service.
	 *
	 * @param status the status of this api service
	 */
	public void setStatus(String status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.opencps.api.model.ApiService apiService);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.opencps.api.model.ApiService> toCacheModel();

	@Override
	public org.opencps.api.model.ApiService toEscapedModel();

	@Override
	public org.opencps.api.model.ApiService toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}